### ISSUE TITLE
preserve empty rows

### ISSUE THREAD

**Issue by emmettnicholas** [adaltas/node-csv-parse#12]
```
csv.parse('a\nb\n\nc', function(err, rows) {
    console.log(rows);
});
```

results in `[ [ 'a' ], [ 'b' ], [ 'c' ] ]`

whereas I expected `[ [ 'a' ], [ 'b' ], [''], [ 'c' ] ]`

**Comment by pkyeck** [comment]
is there also a way to ignore "empty" rows that look like this:

```
a;b;c
d;e;f
;;
;;
g;h;i
```

I want the output to be 

```
[
  ["a", "b", "c"],
  ["d", "e", "f"],
  ["g", "h", "i"]
]
```

instead of 

```
[
  ["a", "b", "c"],
  ["d", "e", "f"],
  ["", "", ""],
  ["", "", ""],
  ["g", "h", "i"]
]
```

because the CSV files I'm handling right now contain a lot of these "empty" rows ...

**Comment by wdavidw** [comment]
not in this module but you could use [transform](http://csv.adaltas.com/transform/) for this
