### ISSUE TITLE
Option from & to not working

### ISSUE THREAD

**Issue by vannleonheart** [adaltas/node-csv-parse#132]
I set the option from & to value, but it's not working properly.
But when I add 

`this.count++`

after line 234 on file lib/index.js, tada.. it came to work.

**Comment by MarcusSpecht** [comment]
From/to options also not working for me.

**Comment by wdavidw** [comment]
Those fonctionnatilities came from a pull request a while ago, I personnally only reviewed them with their associated tests. Would it be possible to write a small test or sample to illustrate your issue ? That would help a lot in fixing it.

**Comment by vannleonheart** [comment]
I already resolve this issue by adding `this.count++` on file lib/index.js around line 234. But I don't mind to write the test for you.

**Comment by wdavidw** [comment]
Thanks, i would appreciate. I wasnt asking for the solution but a way to quickly reproduce the error.
