### ISSUE TITLE
Spaces before quotation marks cause problems.

### ISSUE THREAD

**Issue by annamaz** [adaltas/node-csv-parse#138]
I have .csv file formatted in the following way:

<img width="184" alt="screen shot 2017-05-24 at 12 00 53" src="https://cloud.githubusercontent.com/assets/22752759/26398159/ee231f64-4078-11e7-98d2-04e7364ff3e8.png">

Opened in Microsoft Excel it looks like this:

<img width="166" alt="screen shot 2017-05-24 at 12 01 03" src="https://cloud.githubusercontent.com/assets/22752759/26398179/ff358ab2-4078-11e7-9726-7d93374a0b80.png">

It is caused by spaces before quotation marks.

However, CSV parser throws an error: 
> Error: Invalid opening quote at line 2

WIKI: 
> According to RFC 4180, spaces outside quotes in a field are not allowed; however, the RFC also says that "**Spaces are considered part of a field and should not be ignored.**" and "Implementors should 'be conservative in what you do, be liberal in what you accept from others' (RFC 793 [8]) when processing CSV files."
1997, "Ford" ,E350 
(source: https://en.wikipedia.org/wiki/Comma-separated_values)

**Comment by wdavidw** [comment]
I believed I tried once to make it work and CSV specs are unclear. One solution is to disable quoting (`quote: ''`). This is also related to the "relax" option which is buggy.

**Comment by nschwan94** [comment]
just spitballin' but would the `trim` option be appropriate here to avoid this type of issue?

**Comment by wdavidw** [comment]
Yes, `trim` should do it, closing.

**Comment by mbaquerizo** [comment]
Hi,
`trim` isn't doing it for me for some reason. Still getting the Invalid opening quote error. 
On the latest release. Any ideas?

example of a line i am trying to parse:
```
"B00V5MDI8S","Plantation Trilogy: Deep Summer, The Handsome Road, and This Side of Glory","0.91%","-88.28%","2,931.58%","-88.47%","2,406.67%","98.38%","-30.03%","259.55%","—","—","—"
```

**Comment by wdavidw** [comment]
`trim` apply to spaces outside of the quotes, which you don't seem to have in your data sample.

**Comment by wdavidw** [comment]
It seems to works correctly, I just tried to paste your data in the [convertor tool](https://csv.js.org/convert/) and it output the parsed array as expected.

**Comment by mbaquerizo** [comment]
@wdavidw Thanks for the converter tool link! Sorry for not giving more info, but playing with the converter tool helped. It seems to have been the `record_delimiter` option set to `'\n'` that was causing the error. Looking into that option now to see if we really need it.
