### ISSUE TITLE
Double quote within field surrounded by double quotes

### ISSUE THREAD

**Issue by alexfaber2011** [adaltas/node-csv-parse#14]
First off, great work! The parser works great on another CSV of mine that mixes double quotes in intermittently.

The parser chokes on this line:
 `"FOOBAR "MICK" SELF","FOOBAR COMPANY"`

Spits our this error
`[Error: Invalid closing quote at line 654; found "M" instead of delimiter ","]`

All fields in this CSV are surrounded by double quotes. 

Here's my code (using Meteor.js and coffeescript; sorry):

``` coffeescript
future = new Future()
  parse = Meteor.require('csv-parse')
  parse csv, {delimiter: ','}, (error, result) ->
    if error
      console.log "[csv_to_array] error: ", error
    else
      console.log "[csv_to_array] result: ", result
      future["return"](result)
  return future.wait()
```

Is there a way to get around this? I believe the parser is defaulted to deal with double quotes, but not in this way apparently.

**Comment by markstos** [comment]
I also ran into a problem with a nick name in a field, but mine didn't have quotes around the filed, just the the nick name: `Jack "Joe"`.

I tried to parse the file with the option set to: ` escape: '"'`, but resulted in: `Invalid opening quote at line 1117`

I tried again, not setting the `escape` option at all, and got the same result. 

I had thought the CSV originated from LibreOffice could be considered a quality input. However, after opening and re-saving the CSV file in LibreOffice, I see it quoted the field for me: `"Jack ""Joe"" "`, which should import fine. 

So just a note to others who run into this problem: If you can, try round-triping the failing CSV through LibreOffice to improve the quoting if that's an option for you.

**Comment by wdavidw** [comment]
try the relax option, it is illustrated in [this test](https://github.com/wdavidw/node-csv-parse/blob/master/test/quote.coffee#L34-L44)

**Comment by markstos** [comment]
Based on the test case, that would have addressed my case. The `relax` option just needs a bit of documentation [here](https://github.com/wdavidw/node-csv-parse#parser-options).
