### ISSUE TITLE
Automatic rowDelimiter discovery should ignore newlines in quoted fields

### ISSUE THREAD

**Issue by ctstone** [adaltas/node-csv-parse#142]
Repro:

```JavaScript
const content = 'one\ttwo\t"three.1\nthree.2"\r\nfour\tfive\tsix\r\n';
const options = {delimiter: '\t'}
csvParse(content, options, (err, data) => {
    if (err) throw err;
    console.log(data);
});
```

Results in Error: `Invalid closing quote at line 2; found "\r" instead of delimiter "\t"`. I get the the same error if I explicitly set `rowDelimiter` to `\n` in my options.

I would expect the auto-discovery to ignore the first newline it finds (`\n`) since it occurs in a quoted value.

The problem goes away when the correct value is explicitly set in options, `{delimiter:'\t', rowDelimiter:'\r\n'}`.

**Comment by ctstone** [comment]
Also, am I mistaken or are the constants 'auto', 'unix', 'mac', 'windows', 'unicode' never recognized for rowDelimiter, and instead treated as literals?

**Comment by wdavidw** [comment]
They are literal and are converted to rowDelimiter, for exemple, the value "windows" is converted to "\r\n".

**Comment by wdavidw** [comment]
When I execute your sample, I get

```
[ [ 'one', 'two', 'three.1\nthree.2' ],
  [ 'four', 'five', 'six' ] ]
```

Which seems to be the expected behavior unless i'm missing something.

**Comment by ctstone** [comment]
Are you sure you are running the same code? Here is an online repro:
https://runkit.com/ctstone/csv-parse-row-delimiter-error

RE: constants, the string literal 'windows' does not appear in source:
https://github.com/wdavidw/node-csv-parse/search?utf8=%E2%9C%93&q=windows&type=

so i'm wondering where the conversion happens.

In fact, if I peek at the parser's options I can see that the value is still 'windows':
```JavaScript
> let options = {delimiter: '\t', rowDelimiter: 'windows'}
> console.log(csvParse(content, options, () => null).options.rowDelimiter)
[ 'windows' ]
```

And another repro showing that conversion is not happening:
https://runkit.com/ctstone/csv-parse-rowdelimiter-constants

**Comment by wdavidw** [comment]
This test pass for me: https://runkit.com/ctstone/csv-parse-row-delimiter-error
I'm using version 1.2.1 of csv-parse.

**Comment by wdavidw** [comment]
About the literal, I was wrong, I'm myself got confused. I believed it was part of a very old version of the parser and the doc was never updated to reflect its removal.

**Comment by ctstone** [comment]
1.2.1 works for me as well, but is not yet published to NPM

Looks like a lot changed from 1.2.0. Guessing it's [this line](https://github.com/wdavidw/node-csv-parse/compare/v1.2.0...v1.2.1#diff-f35c5932bb4da98c9da8192a6851d827R275) that fixed it.

**Comment by wdavidw** [comment]
Sorry, it should have been published. It is now.
