### ISSUE TITLE
Combination of 'from', 'columns' and 'relax_column_count: false' and 'error' event

### ISSUE THREAD

**Issue by elutz** [adaltas/node-csv-parse#144]
I use the above mentioned options. I have to use

- `from` because the first lines of the csv contains some unparseable comments
- I use the `columns` option too, since I want a certain object as the result of the parsing, the defined `columns` array matches the first parseable line in the csv
- and 'relax_column_count: true'

But I want to check the validity of the csv beginning with the defined `from` line. So I thought I set 'relax_column_count:' to `false`. But in this case every time an error is thrown since the the lines before the `from` line don't match the columns array.
The error is: 

> Number of columns on line 1 does not match header

But I want the data starting from say line 4, per specification this line is ok, if it isn't ok, then the error should be thrown. I'm not interested in line 1 to 3.
And there are also some unimportant footer lines in the csv. These lines shouldn't cause an error too.

Is there a way to solve this problem or is this something to fix in the code of the cvc-parser.

Regards
Lutz

**Comment by wdavidw** [comment]
Doing some cleanup, feel free to re-open a new issue.
