### ISSUE TITLE
Relax:true adds `"null` to certain entries

### ISSUE THREAD

**Issue by alubbe** [adaltas/node-csv-parse#149]
I am trying to parse row that contain non-quoted entries with escaped quotes inside of them, like this one:
```
some entry,""Surrounded by escaped quotes"" entry continued,next entry
```
This cannot be parsed without using `relax:true`. But with `relax` enabled, we suddenly get some extra characters (`"null`):
```js
[ 
  'some entry',
  '"null"Surrounded by escaped quotes" entry continued',
  'next entry' 
]
```
I believe this is a bug - or am I missing something?

You can reproduce this by running this in the cli:
```
node -e "console.log(string=\`some entry,\"\"Surrounded by escaped quotes\"\" entry continued,next entry\`);require('csv-parse')(string, {relax:true}, console.log)"
```

**Comment by wdavidw** [comment]
I must admit there has always been some problem around the `relax` option, i'll try to take a look.

**Comment by wdavidw** [comment]
This should now be fixed witht the latest release, expect `'"Surrounded by escaped quotes" entry continued'`,

**Comment by alubbe** [comment]
Thank you for this incredibly fast fix! I've done a quick code review and found a minor typo: https://github.com/adaltas/node-csv-parse/pull/150
