### ISSUE TITLE
Getting "ReferenceError: Invalid left-hand side in assignment" when running

### ISSUE THREAD

**Issue by sgerace** [adaltas/node-csv-parse#163]
We're using an old version of the csv package (v0.4.6) in one of our projects and this morning when I went to install on a new machine, I'm now getting the following error reported from the csv-parse package:

```
./node_modules/csv/node_modules/csv-parse/lib/index.js:15
({StringDecoder} = require('string_decoder'));
 ^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./node_modules/csv/lib/index.js:6:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

We're also running an older version of node (v4.2.4). Any help would be greatly appreciated as I'm currently unable to create any new installations of our software.

**Comment by sgerace** [comment]
This seems to be related to the move from CoffeeScript 1.x to CoffeeScript 2.x, you can see pretty clearly when you compare the `index.js` file that I pulled down yesterday to the one that I am now getting:

`csv-parse/lib/index.js` from yesterday:
```
// Generated by CoffeeScript 1.9.3
var Parser, StringDecoder, stream, util;

stream = require('stream');

util = require('util');

StringDecoder = require('string_decoder').StringDecoder;
```

`csv-parse/lib/index.js` from this morning (after this morning's deployment to 1.3.0:
```
// Generated by CoffeeScript 2.0.1
// # CSV Parser

// This module provides a CSV parser tested and used against large datasets. Over
// the year, it has been enhance and is now full of useful options.

// Please look at the [README], the [project website][site] the [samples] and the
// [tests] for additional information.
var Parser, StringDecoder, isObjLiteral, stream, util;

stream = require('stream');

util = require('util');

({StringDecoder} = require('string_decoder'));
```

Clearly the `({StringDecoder} = require('string_decoder'));` is ES6 syntax, which, at this time, I believe is only natively supported in Node 7.6+. Is there any way to go back to an older version of CoffeeScript that still exports ES5? The problem is that this was caused indirectly because the `csv` package (which we require a fixed version) requires `csv-parse` as `"csv-parse": "^1.0.0"` so even though we didn't upgrade the `csv` package version, the underlying `csv-parse` package was updated to `1.3.0` and hence everything is now broken for us.

**Comment by sgerace** [comment]
Alternatively, since this is a major breaking change for anyone running a non-ES6 compatible version of node, an alternative solution might be to change the version number to `2.0.0` and remove the `1.3.0` version from `npm`.

**Comment by wdavidw** [comment]
Migrating to CoffeeScript was not expecting to be a major breaking change, could you try the latest version 1.3.1, it shall fix you're issue (if there ain't to be another one).

**Comment by wdavidw** [comment]
Hum, removing the destructing assignemet probably wont be enough because i saw some default option parameter. I think going the 2.x route might be better.

**Comment by wdavidw** [comment]
Ok, I have updated a new minor version of each module with CoffeeScript 1, now I'll regenerate the code with version 2 and bump a major version.

**Comment by wdavidw** [comment]
If I havent made any mistake, it shall be ok now, thanks for reporting.

**Comment by sgerace** [comment]
Thanks @wdavidw, I just tried reinstalling all of my node modules and so far it seems to be working again. I'll let you know if I run into any other issues. I appreciate the quick reply and fix.
