### ISSUE TITLE
ES6 Template strings break uglifyJS in webpack 2.

### ISSUE THREAD

**Issue by wildeyes** [adaltas/node-csv-parse#165]
Running `webpack -p` on code that requires `csv-parse` breaks, because of the line ```throw Error(`Invalid callback argument: ${JSON.stringify(callback)}`);```. Just letting people out there know, and if possible to not use template strings or compile le code, that would make it work, but that's too much to ask for little gain :)

Thanks for the great library.

**Comment by wdavidw** [comment]
Version 2.x is generated by CoffeeScrit 2. Thus, it targets ES6 and above and requires some transformation (eg babel). Version 1.x remains available and compatible with standart JS. Opinions on this approach are welcome.
