### ISSUE TITLE
.read() returns null when using stream API

### ISSUE THREAD

**Issue by kennyczadzeck** [adaltas/node-csv-parse#167]
When piping a fs.createReadStream object into a parser instance, calling parser.read() on the 'readable' event always returns null. I'm having the exact same issue as the people in this thread, which features a similar code example.
https://stackoverflow.com/questions/35322379/reasons-why-a-node-stream-read-function-might-return-null

The same input data works fine when using the callback API.

**Comment by wdavidw** [comment]
This is documented in on [Stream API](https://nodejs.org/api/stream.html#stream_readable_read_size) page, you should wait for the 'readable' event before calling read. There are multiple examples in the tests illustrating on to use this mechanism, such as [this one](https://github.com/adaltas/node-csv-parse/blob/master/test/api.pipe.coffee#L13-L15). Do you confirm this answer fix your problem ?

**Comment by kennyczadzeck** [comment]
Unfortunately, that does not fix the problem. I used that page and those examples as references when trying to first get it working. I came across the SO thread while looking for clues. 

Here is my code

```
searchCsv(dbInsert) {
  /*
    Searches the CSV stream for rows who's UPC field 
    is in the list property set.
  */
  const parser = CsvParser(this.csvCfg);
  parser.on('readable', () => {
    let data;
    console.log(parser.read()); // <- Null
    while(data = parser.read()) {
      console.log(data); // <- Never runs due to parser.read() returning null
      if (this.list.has(data.digital_upc)) {
        dbInsert(data.digital_upc, data.US_digital_asin);
      }
    }
  });
  fs.createReadStream(this.csvFile, {encoding: 'utf-8'}).pipe(parser);
  parser.end();
}
```

**Comment by wdavidw** [comment]
You are not expected to end the parser on the last line. Also, you must put `dbInsert` inside a stream writer  or you'll overflow your system. You can use stream-transform for that with the consume option on or implement your own function.

**Comment by iakovoszournatzis** [comment]
> You are not expected to end the parser on the last line. Also, you must put `dbInsert` inside a stream writer or you'll overflow your system. You can use stream-transform for that with the consume option on or implement your own function.

Can you give an example?

Thanks!

**Comment by wdavidw** [comment]
It would look someting like

```js
parse = require('csv-parse')
transform = require('stream-transform)
config = {}
fs.createReadStream(this.csvFile, {encoding: 'utf-8'})
.pipe(parse(config))
.pipe(transform({
  consume: true
}, function(record){
  dbInsert(record)
})
```
