### ISSUE TITLE
Pause Node csv-parser when uploading data

### ISSUE THREAD

**Issue by AjayThomas-okta** [adaltas/node-csv-parse#168]
I am working with Node csv-parser and my read stream is from std in. I am piping that to the parser. Inside the parser readable function, I am making an async HTTP call to upload this data. During this time, I want the parser to pause reading. Until the async call has finished excecuting.

```
var parse = require('csv-parse');
 var output = [];
// Create the parser
var parser = parse({delimiter: ',', columns: true, trim: true});
  
parser.on('readable', function () {
    while (record = parser.read()) {
      console.log('Still reading');
      var jsonData = JSON.stringify(record);
      output.push(new Buffer(jsonData + "\n"));
      //parser.pause();
      var assertPromise = uploadBatches1(output, function() {
          //parser.resume();
          console.log('Returned');
      });
     }
});

function uploadBatches1(output, cb) {
    //uploads data got form parser
}
```

In the above code, I see logs Still reading repeatedly being printed even before http call returns.

I am not using any transform.

**Comment by wdavidw** [comment]
You should use a stream reader to send your HTTP request and not attempt to throttle the streaming chain yourself. For exemple with stream-stransform:

```
process.stdin
.pipe( parse({delimiter: ',', columns: true, trim: true}) )
.pipe( trasform(function(data, callback){
  uploadBatches(data, function(){
    callback()
  })
}, consume: true)
```

**Comment by wdavidw** [comment]
You should use a stream reader to send your HTTP request and not attempt to throttle the streaming chain yourself. For exemple with stream-stransform:

```js
process.stdin
.pipe( parse({delimiter: ',', columns: true, trim: true}) )
.pipe( trasform(function(data, callback){
  uploadBatches(data, function(){
    callback()
  })
}, consume: true)
```

**Comment by AjayThomas-okta** [comment]
Thanks @wdavidw, that worked!

**Comment by AjayThomas-okta** [comment]
Thanks @wdavidw, that worked!
