### ISSUE TITLE
How do you escape the escape character?

### ISSUE THREAD

**Issue by seantcanavan** [adaltas/node-csv-parse#169]
What happens if there's a double quote in the data? Initial testing shows this won't work and throws `Invalid closing quote at line XYZ; found 'character' instead of delimiter ","` error.

What is the correct way to escape the currently defined escape character so that it's input as a raw value?

Test input:
id, name
"12345", "My "Name" is Name"

**Comment by seantcanavan** [comment]
After a lot of trial and error with various values for escape, quote, and delimiter I've gotten this to work without muddling up my data. Weirdly I had trouble finding some good examples of less-than-stellar data when using google.

**Comment by wdavidw** [comment]
You should also look at the tests, they are easy to read and cover the majority if not every usecase.
