### ISSUE TITLE
Is there any way to escape comma that match certain regex pattern 

### ISSUE THREAD

**Issue by shengtaoli** [adaltas/node-csv-parse#171]
I want to keep a company name together: ("Acme, Inc")
I am not aware if there's an option currently that support escaping certain comma
(i.e., comma that's surrounding in a double quote)

**Comment by wdavidw** [comment]
Could you provide a one line example illustrating your request, I dont understand what you mean by "certain" and wether or not you have quotes.

**Comment by shengtaoli** [comment]
Name, CompanyName, ContactInfo
Test1, "Acme, Inc", 123-45-6666

**Comment by wdavidw** [comment]
You're problem comes from the space between to two field. Using `trim` should fix it:

```coffee
parse """
Name, CompanyName, ContactInfo
Test1, "Acme, Inc", 123-45-6666
""", trim: true, (err, data) ->
  console.log err, data
```
