### ISSUE TITLE
Sparse Parse?

### ISSUE THREAD

**Issue by jhihn** [adaltas/node-csv-parse#174]
I have a need to more efficiently scan large CSVs. I'm in most cases returning less than 1% of the data in the file. 

In order to come up with a faster way of extracting the data I am looking for, I can make an row-offset map to the beginning of each row I'm looking for. I then want to feed the offsets into the parser, which will seek(offset) then parse these rows as normal, then seek, parse 1 row (and only one row only), repeat until end of list. However I understand node is inherently async, as well as the reads are probably based on block reads and not row oriented? I know all the offsets for the file up front, but I can imagine async purists wanting some kind of offset generator... But I'd be happy with an array.

Is there anyway to do this with this package? 

EDIT: So I think the proper approach to this is to come up with a "quoted multi-line reader" (of which this package has logic for parsing) which seeks then extracts the potentially-multi-line-rows from the source stream, sending on a stream of only rows of interest to the parser. The thing is the "quoted line reader" needs to have the same logic as the parser. The node package Readline is not good enough because of quoted values may contain multiple lines.

1. open file 
2. seek offset
3. readline(s) (potentially several lines, if in a quoted field)
4. send "line" (really an unparsed row of potentially many lines) to parser via stream API
5. goto 2 if offset(s) remain
6. end stream

**Comment by wdavidw** [comment]
I have difficulties to fully understand your request but a fee notes:

- this parser doesnt deal with file, only with string or buffer
- the api is based on the event and stream api for scallability reasons but is otherwise synchronuous, see the "csv-parse/lib/sync" module

**Comment by jhihn** [comment]
Ok, let me explain with an example:

"a","b","c" //0x00-0c
1,2,3 // 0x0c-11
2,3,4 // 0x11-17
3,4,5 // 0x21-27
4,5,"6
text
" //0x27-34 

I have a WORM system (Write once, read many). I can record the offsets to the row starts. {1: 0x0c, 2: 0x11, 3: 0x21, 4: 0x27}
I have a function that tells me what rows I need to read, for this example, it's data row 4. In reality the rows are long, and I only need a few of them at a time.  As it stands, the code is running on a server with provisioned IOPS. On my desktop it's fast enough, but when on the server, it takes minutes. So, since I'm linearly scanning the file and just parsing data that I just throw away, I can save the IOPS and the CPU and place in a few seeks. If I want to read row 4, want to be able to tell whatever stream the file data is coming from to read the first row (at 0x00) to know there are 3 columns, then seek to 0x27 (which I will know ahead of time), read that row to the end of field at 0x34, emit that as a data row.

The problem comes because I want to re-use your very vetted parsing code, and not have to maintain parse code independent of that. It's as if I want to pass just:

"a","b","c"
4,5,"6
text
"
to the parser. The problem is there are newlines in the comment, and so the end of the row has to be determined by the parser.

I probably need to use https://www.npmjs.com/package/fs-readstream-seek and on the parse 'data' event, call seek() on the input stream. But I do not know how to hook the parser and the reader in a stable way.  Things that concern me:

1. Extra bytes in the parser buffer need to be cleared or put back in the stream for adjacent rows (rows in the same read block)
2. Do I need to pass the buffer, or can I just pass byte by byte until I get a 'data' event? How do I determine end-of-row?

**Comment by wdavidw** [comment]
If you need a partial parser, it still feel like 'csv-parse/lib/sync' is a good fit. You could use 'fs-readstream-seek' twice, first to read the header, second to read the bytes corresponding to a record, and call the synchronous parser for each of them. As I wrote earlier, the parser doesnt deal with file reading. It does has options like "from" and "to" but it will still parse the all dataset to know where to start and stop parsing.

**Comment by jhihn** [comment]
Ok thank you. I'll give that a try!

**Comment by jhihn** [comment]
I ended up writing my own stream which then feeds parse. Problem solved.
