### ISSUE TITLE
No changelog for 1.3.3 ?

### ISSUE THREAD

**Issue by yvele** [adaltas/node-csv-parse#175]
Version 1.3.3 is the latest version compatible with node < 7

I can see it on npm:

```sh
> npm view csv-parse

....
     '1.2.1': '2017-07-24T19:50:56.998Z',
     '1.2.2': '2017-09-13T15:59:40.960Z',
     '1.2.3': '2017-09-22T17:59:53.416Z',
     '1.2.4': '2017-10-06T10:48:11.467Z',
     '1.3.0': '2017-10-20T10:27:31.520Z',
     '1.3.1': '2017-10-20T11:29:13.451Z',
     '1.3.2': '2017-10-20T11:44:04.600Z',
     '1.3.3': '2017-10-20T11:47:32.533Z',
     '2.0.0': '2017-10-20T12:04:19.795Z' },
....
```

But it doesn't appears in the releases https://github.com/adaltas/node-csv-parse/releases

Neither in the changelog https://github.com/adaltas/node-csv-parse/blob/master/CHANGELOG.md

Same problem about `1.3.2`

Can we add a little line to the changelog to explain what has changed?

**Comment by wdavidw** [comment]
Thanks for noticing
