### ISSUE TITLE
Setting "require('csv-parse');" include statement causes "unexpected token" error

### ISSUE THREAD

**Issue by BruteFarcical** [adaltas/node-csv-parse#176]
Was mucking around with a script I found somewhere and kept getting this error:

    /path/to/project/script/node_modules/csv-parse/lib/index.js:114
    Parser = function(options = {}) {
    SyntaxError: Unexpected token =

I suspected it was something to do with the script I was using as it hadn't been updated in a long time, so I tried just writing the very basic "callback parser" example located [here](http://csv.adaltas.com/parse/examples/) and ran into the same error.

I then stripped it down to just the `var parse = require('csv-parse')` line and sure enough, same error.

I took a look at the [source code](https://github.com/adaltas/node-csv-parse/blob/master/lib/index.js#L114) to see if maybe there was some extra un-closed bracketing or something, but could not find anything that stood out immediately in the vicinity of that line.

Any ideas? I have a suspicion it is something silly that I am failing to do correctly but I have plinked at it for a few hours now to no avail.

**Comment by wdavidw** [comment]
Use version 1.x if below Node.js 8. That should be the reason.
