### ISSUE TITLE
Module breaks React builds

### ISSUE THREAD

**Issue by varffs** [adaltas/node-csv-parse#177]
I cannot use this package direcly with React as during build `lib/index.js` fails to minify.  The React app tool provided this documentation of the issue: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

It would be nice if this package could work out the box with React. For the moment I will just likely include the source in my app code but just bringing this issue to your attention. Thanks for a nice package.

**Comment by wdavidw** [comment]
You have 2 solutions: use versions 1.x which is for now align with versions 2.x or use a transpilation tool like babel.

**Comment by varffs** [comment]
Using 1.x is a working solution for me so thank you.

**Comment by maciekmpintive** [comment]
hm, maybe branch 2.X.X should also build to es5?

**Comment by wdavidw** [comment]
Not sure I understood your message. Isn't it already what it [does](https://github.com/adaltas/node-csv-parse/tree/master/lib/es5)?

**Comment by maciekmpintive** [comment]
thanks for a response! I added this package to my app 2 days and go and described error with minification still occurs so maybe the issue is somewhere else?
