### ISSUE TITLE
Misnamed variable on line 438

### ISSUE THREAD

**Issue by snggeng** [adaltas/node-csv-parse#179]
Hi I was noticed that there is an unreachable variable on line 438 of `node-csv-parse/lib/index.js`: 
*Line 438*
```
      if (this.raw) {
          rawBuf += this._.nextChar;
        }
```

Should look like this:
```
this._.rawBuf += this._.nextChar
```

I spotted this error while using the parent module `node-csv` or `csv` (in npm) in a React.js project and it refused to build because the modules don't support `ES5` syntax. I required your source files as a source dependency directly in my project and took a look at them while doing that. 

Let me know if this is a valid issue and if I should file a PR to fix it! Thanks.

**Comment by wdavidw** [comment]
Good catch, thanks.
