### ISSUE TITLE
Feature request: Default value for inconsistent number of columns

### ISSUE THREAD

**Issue by iffy** [adaltas/node-csv-parse#181]
I'm parsing some CSV files where columns are omitted if blank.  For instance:

```
name,age,notes
John,10,Likes basketball
Sam,12
Sarah,13,Made cookies
```

Could I somehow supply a default value for Sam's `notes` field?

**Comment by iffy** [comment]
Maybe `relax_column_count` is what I want?

**Comment by wdavidw** [comment]
Looking at the [tests](https://github.com/adaltas/node-csv-parse/blob/master/test/options.relax_column_count.coffee), it seems to do the job. Please re-open if it doesnt.
