### ISSUE TITLE
Exception on csv-parse: “SyntaxError: Unexpected token {“

### ISSUE THREAD

**Issue by beetleX** [adaltas/node-csv-parse#183]
**Getting Same Exception on sample “fs_read.js”**

node ./fs_read.js
/home/pi/projects/temp-and-humidity/node_modules/csv-parse/lib/index.js:114
Parser = function(options {}) {
                          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/projects/temp-and-humidity/node_modules/csv-parse/samples/fs_read.js:3:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**used "version": "2.0.4"**

**Comment by wdavidw** [comment]
You are probably using an old version of Node.js. If this is the case, either `var parse = require('..');` to `var parse = require('../lib/es5');` or upgrade to a version equal or above 8.

**Comment by beetleX** [comment]
thanks for the feedback
node --version
v9.8.0
so this shouldn't be the issue

**Comment by wdavidw** [comment]
it work for me

```
> node -v
v9.9.0
> node fs_read.js
[ [ 'abc', '123' ], [ 'def', '456' ], [ 'ghi', '789' ] ]
```

**Comment by wdavidw** [comment]
You're error definitely looks like if you dont support es6.

**Comment by losiz17** [comment]
Packaging app for platform darwin x64 using electron v1.4.13

Uncaught SyntaxError: unexpected token ...
at node_modules/csv-parse/lib/index.js:20

Using environment：
$node -v 
v11.10.1

$npm -v
6.9.0

**Comment by wdavidw** [comment]
Could you try using "csv-parse/lib/es5", it shall work. I don't use electron but while your Node.js version v11.10.1 support destructuring arguments, maybe electron package an older version of Node.js ?

**Comment by losiz17** [comment]
I used "require("csv")" 
 changed "require("csv-parse/lib/es5)" it works.
Thank you:)
