### ISSUE TITLE
Sync Api handles Errors on last line differently from other lines

### ISSUE THREAD

**Issue by Typhlosaurus** [adaltas/node-csv-parse#184]
In csv-parse release 2.0.4

Passing
```
headerA, headerB
A1, B1
A2, B2, C2, D2
```

to the sync parser returns [{headerA: "A1", headerB: "B1"}], whereas:
 ```
headerA, headerB
A1, B1, C2, D2
A2, B2
```

throws an `Error('Number of columns on line 2 does not match header')`.  

This seems to be caused by the lack of a callback on line 38 (`parser._flush((function() {}));`) of `csv-parse/lib/sync.js`

**Comment by wdavidw** [comment]
Thank you, will be published soon (today)

**Comment by Typhlosaurus** [comment]
That was quick!  Thanks.
