### ISSUE TITLE
nulls vs empty strings

### ISSUE THREAD

**Issue by dkloke** [adaltas/node-csv-parse#185]
Thank you for this library.

I have CSV files where all strings are quoted, even if they're empty, but a sequence of two consecutive commas indicated `null`.

Where a row is: `1,"2",,""`
I would like this row returned as: `[1,'2',null,'']`.

I have also seen, and may need to work with, files with rows like: `1,"2",null,""` where the unquoted 'null' (or similar) should be returned as an explicit `null` in the result array. For example:
`1,null,"3","null",5` => `[1,null,'3','null',5]`.

I imagine this implemented as a parser option:

   -  consider_null (false|string) default _false_. 

If the setting is false, no recognition of nulls will occur (current/default behavior). If the setting is '' (empty string), then consecutive commas signify nulls. If the setting is some string, occurrence of that string will signify `null` in the output. That string could include double quotes: 
`{consider_null:'"NULL"'}`
`1,"2","NULL",4,null`=>`[1,'2',null,4,'null']` 

Of course, checking for these cases will impact performance. It may be faster to scan a line for the case rather than checking each value, and activate the per-value check if it's found:
```
if(this.options.consider_null!==false){
  const hasNulls = new RegExp(`(^|,)${this.options.consider_null}(,|$)`)
  if( row.match( hasNulls) ) {
    //implement per-value test

```
Obviously it's more complicated, since the comma can also be redefined, this example for demo of concept. And this could also change interpretation of empty rows :p

And if performance is really poor, just the option to handle the two-consecutive-commas case would be a great boon. Thank you for considering this feature!

**Comment by wdavidw** [comment]
The latest version I just published will allow you to achieve what you wish, at least I hope so. When passing a user defined function to "cast" (previously named "auto_parse", you get a second context argument which contains a property quoting. here's an example:

```coffee
parse = require '.'
parse """
1,"2",,""
""",
  cast: (value, {quoting}) ->
    if value is ''
      if quoting then '' else null
    else value
, console.log
# [ '1', '2', null, '' ]
```

And

```
parse = require '.'
parse """
1,"2","NULL",4,null
""",
  cast: (value, {quoting}) ->
    if value.toLowerCase() is 'null'
      if quoting then value else null
    else value
, console.log
# [ '1', '2', null, '4', 'null' ]
```

**Comment by dkloke** [comment]
Works nicely, very flexible, thank you!

**Comment by edsu** [comment]
As a new user coming from Python's csv module I expected the default behavior for missing values to be `null`, not an empty string `'""`:

    'foo',,'bar'

would yield:

    ['foo', null, 'bar']

instead of:

    ['foo', '', 'bar']

**Comment by wdavidw** [comment]
That would be too intrusive for a default behavior. You provide an empty CSV field, you get an empty JS string. However, I am not against an option such as `cast_empty_to_null` if anyone want to submit it.
