### ISSUE TITLE
"auto_parse" option as function object receive wrong information?

### ISSUE THREAD

**Issue by osddeitf** [adaltas/node-csv-parse#188]
I have a csv file like this:

    a, b, c, d
    1, NULL, 'abc', 1.6
    2, NULL, NULL, 2.5

The first line is header, when I parse like this:
    
    const parse = require('csv-parse/lib/sync')

    const options = {
      columns: true,
      quote: "'",
      trim: true
    }
    const csv = fs.readFileSync('data.csv')
    const o = parse(csv, options)

It works as expect, output after `console.log(JSON.stringify("o", null, 2))`:

    [
      {
        "a": "1",
        "b": "NULL",
        "c": "abc",
        "d": "1.6"
      },
      {
        "a": "2",
        "b": "NULL",
        "c": "NULL",
        "d": "2.5"
      }
    ]

But now I want to convert to Js type, when I add "auto_parse" option:

    auto_parse: function (value, information) {
      console.log(value, information)
      if (information.quoting) return value
      if (value === 'NULL') return null
      if (value.includes('.')) return Number.parseFloat(value)
      return Number.parseInt(value)
    }

It output:

    [
      {
        "NaN": 1.6
      },
      {
        "NaN": 2.5
      }
    ]

With `console.log(value, information)`, I found:

    a { quoting: false, count: 0, index: 0, column: 0 }
    b { quoting: false, count: 0, index: 1, column: 1 }
    c { quoting: false, count: 0, index: 2, column: 2 }
    d { quoting: false, count: 0, index: 3, column: 3 }
    1 { quoting: false, count: 0, index: 0, column: NaN }
    NULL { quoting: false, count: 0, index: 1, column: NaN }
    abc { quoting: true, count: 0, index: 2, column: NaN }
    1.6 { quoting: false, count: 0, index: 3, column: NaN }
    2 { quoting: false, count: 1, index: 0, column: NaN }
    NULL { quoting: false, count: 1, index: 1, column: NaN }
    NULL { quoting: false, count: 1, index: 2, column: NaN }
    2.5 { quoting: false, count: 1, index: 3, column: NaN }

If this seem to be happened because the "auto_parse" option override the columns option, and you see, it should not. My installed library' version is the latest (2.2.0). I hope it'll be fixed soon, thanks

**Comment by wdavidw** [comment]
You are getting `NaN` because you are converting the header field to an integer with `parseInt`. This is because the headers are passed to the `cast` function. To ease the detection of header, we are now passing a `header` property as boolean in version 2.3.0 (just published). You function should now looks like:

```
auto_parse: function (value, information) {
  if(information.header) return value;
  if (information.quoting) return value
  if (value === 'NULL') return null
  if (value.includes('.')) return Number.parseFloat(value)
  return Number.parseInt(value)
}
```
