### ISSUE TITLE
"escape" option error

### ISSUE THREAD

**Issue by osddeitf** [adaltas/node-csv-parse#189]
I found an error on escaping, here is my test code, it failed in the second test case:

    const parse = require('csv-parse/lib/sync')

    describe("escape", () => {
      it('Escape with no space around delimiter', () => {
        const string = `1,'''A'' comes before ''B'' in the alphabet.'`
        parse(string, { quote: "'", escape: "'" })
      })
      it('Escape with space around delimiter with trim option enabled', () => {
        const string = `1, '''A'' comes before ''B'' in the alphabet.'`
        parse(string, { quote: "'", escape: "'", trim: true })
      })
    })

**Comment by wdavidw** [comment]
I just published version 2.4 which shall fix your issue.
