### ISSUE TITLE
Parsing Non-english data issue

### ISSUE THREAD

**Issue by TejasCMehta** [adaltas/node-csv-parse#19]
I am trying to upload csv file which is having non-english data inside. Once file placed in uploadDir, I am trying to read that file line by line and saving them in mongoDB.

But when I read that file I am getting data as `?????????` in database. Also I tried to write those data to another file with below code : 

``` javascript
var path = './mycsv/' + csvFile.path + csvFile.basename;
                csv()
                    .from.options({
                        delimiter: '\t',
                        columns: false
                    })
                    .from.path(path)
                    .on('record', function(row, index) {
                        if (index != 0) {
                            console.log(row[1]);
                            var wstream = fs.createWriteStream('./mycsv/test2.csv');
                            wstream.write(row[1] + '\n');
                            wstream.end();
                        }
                        //console.log(row);
                    })
                    .on('end', function() {
                        console.log('done parsing');
                        cb();
                    })
                    .on('error', function(err) {
                        console.error(err);
                    });
```

but still it print data `à¦¶à§à¦­ à¦¨à¦¬à¦¬à¦°à` . 

Any help ??

**Comment by ambodi** [comment]
Why is this issue closed without further explanation?

I am facing the same issue with ISO-8859-1 encoded CSV file I am parsing.  @wdavidw

**Comment by wdavidw** [comment]
dont expect help unless u provide more information. this has been explained above. In this issue, encoding was not the concern of the CSV parser and shall be handled before passing content to the parser.

**Comment by eugene1g** [comment]
For future Googlers, this fixes the problem -

1. Make sure your original file is saved as UTF or the target encoding. You can check the file encoding by running `file mydata.csv`. 
2. If the file was exported with Excel, it likely has wrong encoding on it so you need to open it with an editor that understands and can force file encodings. Sublime editor works well - just open the CSV file, then use File -> 'Save with Encoding' to convert. Or `iconv -t UTF8 mydata.csv > data-utf8.csv`
3. Then just read it as usual before passing for processing `const csvText = fs.readFileSync('./data-utf8.csv', {encoding: 'utf8'})`

Fixed my problems.

**Comment by shreyaspadhye3011** [comment]
Thanks @eugene1g for sharing this. Found this to be a quick and easy solution

**Comment by ggendre** [comment]
If you can't run a command line, you can use the node package `iconv-lite` to convert your stream on the fly before giving it to the parser like this :

```
fs.createReadStream('file-in-iso88521.csv')
    .pipe(iconv.decodeStream('ISO-8852-1'))
    .pipe(iconv.encodeStream('UTF-8'))
    .pipe(parser);
```

**Comment by uullrich** [comment]
> If you can't run a command line, you can use the node package `iconv-lite` to convert your stream on the fly before giving it to the parser like this :
> 
> ```
> fs.createReadStream('file-in-iso88521.csv')
>     .pipe(iconv.decodeStream('ISO-8852-1'))
>     .pipe(iconv.encodeStream('UTF-8'))
>     .pipe(parser);
> ```

Thanks for this code snippet. This solved my problem.
