### ISSUE TITLE
" inside a Cell

### ISSUE THREAD

**Issue by axi92** [adaltas/node-csv-parse#191]
I have some line with " in the " "
`"Wappen "Zum Tobackraucher"",48.171113,16.379278`

Is there an option to handle this?

**Comment by wdavidw** [comment]
No, I believe there is no possibility for the parser to handle such scenarios. You will have to disable quoting ("quote" set to `null`) and parse it yourself (eg using "cast").

**Comment by Naitik333** [comment]
Can you give an example of this? I also have some records where there is " in the middle of the record

**Comment by wdavidw** [comment]
The [`cast` option](https://csv.js.org/parse/options/cast/) is documented with an example.

**Comment by Naitik333** [comment]
@wdavidw  Thanks for the prompt reply.
can I use the cast option with the csv-parse CSV() method as an option? I don't want to do the entire CSV parsing logic by myself and only handle quote fields inside some records.

**Comment by wdavidw** [comment]
@Naitik333 not sure I fully understand, i'll attempt to clarify. The `cast` option is an option of csv-parse. My suggestion is to not activate the detection of quotes (set `quote` to an empty string or `false`) on the document and leave it to your code, inside the `cast` function you will provide.
