### ISSUE TITLE
Missing many Typescript typings for parse.Options

### ISSUE THREAD

**Issue by yonilerner** [adaltas/node-csv-parse#196]

**Comment by wdavidw** [comment]
Either provide a pull request or be more specific. I don't use TypeScript myself so you'll have to get your hand dirty.

**Comment by yonilerner** [comment]
The project already has typings so I assumed. My bad. I'll make a PR.

**Comment by wdavidw** [comment]
Thank you. If you are confortable with TypeScript, I'm also interested to have on TypeScript test integrated with mocha. I failed to do so a few weeks ago.

**Comment by yonilerner** [comment]
@wdavidw Can you elaborate on that?

**Comment by wdavidw** [comment]
I wish to add one or two dev-dependency in the package.json with typescript in it, create a test in "test/typescript.ts" which load the parser and validate a few calls. This test shall be written in Mocha so that it is also executed when I run `npm test`. From there, I could enrich it to make sure that in the future we don't have issue like yours where an option is not declared or something wasn't lost due to some evolution.

**Comment by yonilerner** [comment]
Ah I see what you mean. Im pretty sure that for this case you wouldnt actually use mocha. Instead, you would just have the Typescript test file declare a bunch of variables, make function calls, etc. and then run the Typescript compiler on it to see if it complains. Something like:
```typescript
import * as csvParse from 'csv-parse'

csvParse({colum: true})
```
And then in the test script in `package.json`, youd have it be:
```json
 "test": "tsc && mocha test/**/*.coffee"
```
And then `npm test` would fail indicating that "colum" is not a valid field of `Options`

I can do this in my PR as well. May take me a couple days though

**Comment by wdavidw** [comment]
This will check the TypeScript syntax though compilation but I also want to manipulate the TypeScript code from a unit test. This way, I would personally feel much more confident updating the schema myself if I could backup my evolutions with unit tests.

**Comment by yonilerner** [comment]
Hm. Unfortunately I dont know how to do that
