### ISSUE TITLE
skip_lines_with_error not working

### ISSUE THREAD

**Issue by dland512** [adaltas/node-csv-parse#198]
I'm having trouble understanding how to handle errors within single lines so that the parser continues on with the next line. I'm using the `skip_lines_with_error` flag but it doesn't seem to have any effect. If I have a poorly formatted line the entire process stops and results in an error rather than moving on to the next line. Here is some sample code:
```
const parse = require('csv-parse');

csv =
    '"field1","field2","field3"\n' +
    '"val4",""bad" val","val5"\n' +
    '"val1","val2","val3"\n';

const opts = {
    delimiter: ',',
    columns: true,
    skip_lines_with_error: true
};

var output = [];

var parser = parse(csv, opts);

parser.on('readable', function(){
    while(record = parser.read()){
        output.push(record);
    }
});

parser.on('error', function(err){
    console.log('error:', err.message);
});

parser.on('finish', function(){
    console.log('done:', JSON.stringify(output, null, 4));
});
```

Notice the unescaped double quotes in the second line around the word "bad". It should be
`'"val4","""bad"" val","val5"\n'`

but instead it's
`'"val4",""bad" val","val5"\n';`

This is resulting in this error:

> error: Invalid closing quote at line 2; found "b" instead of delimiter ","

I get why the parser throws an error in that case but how do I tell it to log the error and move onto the next line rather than totally stopping? It would seem that maybe the `skip_lines_with_error` option isn't working.

**Comment by wdavidw** [comment]
Sorry, but I won't have the time to dig into your code. You can look at the [skip_lines_with_error tests](https://github.com/adaltas/node-csv-parse/blob/master/test/options.skip_lines_with_error.coffee) to check if it covers your issue and, if not, eventually propose a pull request with enhancements.
