### ISSUE TITLE
Avoid `auto_parse` for values having surrounding quotes

### ISSUE THREAD

**Issue by codenirvana** [adaltas/node-csv-parse#199]
> Using version `1.3.3`

For the following input:
```
1,2,"3",4
```

using following options:
```
{auto_parse:true, trim: true}
```

I am expecting: `[1,2,'3',4]` but everything is parsed to an integer value.

---

To handle this I wrote a custom `auto_parse` function:
```javascript
function autoParse (value) {
    if (value.charAt(0) === '"' && value.charAt(value.length - 1) === '"') {
        // remove surrounding double quotes and skip further parsing
        value = value.slice(1, -1);
    } else if (util.isInt(value)) {
        value = parseInt(value);
    } else if (util.isFloat(value)) {
        value = parseFloat(value);
    } else if (this.auto_parse_date) {
        var m = Date.parse(value);
        value = isNaN(m) ? value : new Date(m);
    }
    return value;
}
```

with following options:
```
{auto_parse: csvAutoParse, trim: true, quote: true}
```

BUT the problem with this is, input like `"Hello, World", 2` is parsed to `['"Hello', 'World"', 2]` instead of `['Hello, World', 2]`.

---

In short:
- Need the `quoting` context like version `2.5.0`
- Can't update to v2 because of older Node version support.
- Finally, avoid parsing values surrounded by quotes.

**Comment by wdavidw** [comment]
Simply write a simple `auto_parse` function and use the second argument which contains the `quoting` property: https://github.com/adaltas/node-csv-parse/blob/master/test/options.auto_parse.coffee#L62-L76

**Comment by codenirvana** [comment]
@wdavidw As mentioned I am using version 1.3.3.
Can't update to v2 because of older Node version support.

**Comment by wdavidw** [comment]
Sorry, I missed this part, you can require './lib/es5/index.js'. It is the same as './lib/index.js' but transpiled with babel for backward compatibility.
