### ISSUE TITLE
question: do not escape quote?

### ISSUE THREAD

**Issue by viyatgandhi** [adaltas/node-csv-parse#201]
I have a csv file with data 
id,name

> 101, john
> 102, O'brian

 data should not escape single quotes in O'brian - currently it parses as:

> ['101', 'john']
> ['102', 'O\\'brian']

I tried various combination with relax and escape but it doesn't seems to be working.
http://csv.adaltas.com/parse/
I do not see any option where can I skip for escaping of quotes

Any suggestions? Thanks

**Comment by wdavidw** [comment]
I doubt about your output: it look more as JavaScript than CSV and in such case it is JS which escape your quote; the  default escape charactere is double quote and won't be needed in you example. Could you provide a more defailed example, explain me how you got this output or, if an object, send me the output with `JSON.stringify` applied to it.

**Comment by viyatgandhi** [comment]
@wdavidw  Thanks for the prompt reply. I did further digging and you are right, it is just the JavaScript representation. CSV parser works fine. Thanks for clarifying.
