### ISSUE TITLE
"finish" event emitted before "readable"

### ISSUE THREAD

**Issue by sophister** [adaltas/node-csv-parse#204]
hi , I have a csv file with **two lines** . and I'm using stream api like this:

```javascript
const fileStream = fs.createReadStream(filePath);
const rows = [];
const parser = parse({
    skip_empty_lines: true,
});
parser.on('readable', () => {
    let record = null;
    while(record = parser.read()){
        rows.push(record);
    }
});
parser.on('error', (err) => {
    console.error('parser.error', err);
});
parser.on('finish', () => {
    console.log('finish rows: ', rows);
});

fileStream
    .pipe(iconv.decodeStream('gbk'))
    .pipe(parser);

```

when `finish` emitted, only 1 rows showed.  using `node v10.6.0` to debug, it turns out that after `finish` event emitted, one more `readable` event is evemitte, and at that time, I can get the second line.

Did I miss something?
thx in advance!

**Comment by wdavidw** [comment]
The parser is both a writable and a readable stream. You write data and you read records. Following [Node.js. stream documentation](https://nodejs.org/api/stream.html), the "finish" event is from the write API and is emitted when the input source has flushed its data. The "end" event is from the read API and is emitted when there is no more data to be consumed from the stream.

**Comment by sophister** [comment]
@wdavidw 
thx, using `end` works.
maybe `Using the stream API` section of [the example doc](http://csv.adaltas.com/parse/examples/) needs to be updated, it is using `finish` event, and may bother others.

**Comment by wdavidw** [comment]
Good catch, thank you
