### ISSUE TITLE
When utilizing the Stream API, only half of the CSV contents are read in by the stream

### ISSUE THREAD

**Issue by cjativa** [adaltas/node-csv-parse#208]
When utilizing the Stream API of CSV-Parse, only half the contents of the CSV are parsed into objects. This appears to happen regardless of the size of the CSV.

You can run `npm install` on the package i am attaching, then run `ts-node test.ts` to see the bug. It reads from the CSV file attached. 
[packages.zip](https://github.com/adaltas/node-csv-parse/files/2417450/packages.zip)

**Comment by wdavidw** [comment]
A little mistake is the source of your problem:

```ts
parser.on('readable', () => {
	let record;
	while (record = parser.read()) {
		output.push(parser.read());
	}
});
```

should be

```ts
parser.on('readable', () => {
	let record;
	while (record = parser.read()) {
		output.push(record);
	}
});
```
