### ISSUE TITLE
Windows empty lines not correctly handled

### ISSUE THREAD

**Issue by psotres** [adaltas/node-csv-parse#220]
Parser is not working correctly when eol is CRLF and there are more than a single empty line in a file (it works if I save the same file using LF line ending).

I've added another test case on test/option.skip_empty_lines and it fails.
```
      it 'skip', (next) ->
        parse """
        ABC\r\n\r\nDEF\r\n\r\n
        """, skip_empty_lines: true, (err, data) ->
          return next err if err
          data.should.eql [
            [ 'ABC' ]
            [ 'DEF' ]
          ]
          next()
```
Not sure why it fails, but it could be related to #126

**Comment by wdavidw** [comment]
Excellent catch! This is now fixed in 4.1.1. It also impacted the `from_line` option for the same reason that we were incrementing the counter by 1 even if the record delimiter length was longer.
