### ISSUE TITLE
I can't find the docs for the 1.3.3 version

### ISSUE THREAD

**Issue by dev-nulls** [adaltas/node-csv-parse#221]
Hey! I have an old version of your library and unfortunately I can't find the docs for the 1.3.3 version anywhere. It would be great if you put them on github. Thanks!

**Comment by wdavidw** [comment]
Commit [f8c98c025b06ec5cd6688f0375d68c0c24cc15c5](https://github.com/adaltas/node-csv-docs/commit/f8c98c025b06ec5cd6688f0375d68c0c24cc15c5) of csv-docs was the last commit before merging to Gatsby and will reveal the old documentation. Another way to look at it is to look at the date of 1.3.3 which was release 20 oct 2017. This match the commit [de80103904026c53970fa4c46815dcc2518edac0](https://github.com/adaltas/node-csv-docs/commit/de80103904026c53970fa4c46815dcc2518edac0) of csv-docs.
