### ISSUE TITLE
how to use read and write stream

### ISSUE THREAD

**Issue by bipinshukla** [adaltas/node-csv-parse#222]
hello guys i m new over here and got confuse how i can use readstream and write stream right now i tried this(i m using this library https://www.npmjs.com/package/csv-parse) 

        fs.createReadStream(path.join(__dirname,"../demofile/Customers.csv"))
            .pipe(parse(options))
            .on('data', function(csvrow) {
                console.log(csvrow);
                //do something with csvrow
                output.push(csvrow);        
            })
            .on('end',function() {
            //do something wiht csvData
            console.log(csvData);
            });
but i don't think it correct way   read and write stream of csv-parse can anyone suggest me how i can use read and write with above code. basically i want to read  a csv file and write it into another csv file **reason** for using read and write stream is because my file size is about 2gb

**Comment by wdavidw** [comment]
You are using the Node.js read stream API correctly. You should listen to the `readable` event. You can look at our [example](https://csv.js.org/parse/api/) for inspiration. If you need to write to a file, you would have to serialize the records, for exemple using [csv-stringify](). You will find an example on how you could pipe between parse -> transform -> stringify [here](https://csv.js.org/project/examples/#using-the-pipe-api). From this exemple, you would need to switch the generator with the file read stream and add a file write stream instead for `process.stdout`.

**Comment by bipinshukla** [comment]
@wdavidw it tried this

            let self=this
            // Use the readable stream api
            fs.createReadStream(this.reader,function(err,filedata){
                if(err) throw err;
                let parser=csv(parseOptions);
                parser.on('readable', function(){
                    let record
                    while (record = parser.read()) {
                        self.data.push(record)
                    }
                })
                // Catch any error
                parser.on('error', function(err){
                    console.error(err.message)
                })
                // When we are done, test that the parsed output matched what expected
                parser.on('end', function(){
                    console.log('The number of objects in the array are' , output.length , 'but it should be 4');
                    console.log(self.data);
                })
                // Write data to the stream
                parser.write(filedata)
                parser.end();

            });
but now i m getting no console output can you tell me what i does wrong
