### ISSUE TITLE
how to wait a readFileSync?

### ISSUE THREAD

**Issue by ppKrauss** [adaltas/node-csv-parse#224]
Or why it is not a "real sync"?

See https://stackoverflow.com/questions/54170238/how-to-wait-a-readfilesync

**Comment by wdavidw** [comment]
The default and main module exported by `csv-parse` implement the Node.js stream API. To use the sync API, you must use the `csv-parse/lib/sync` module. Here's an exemple based on your code posted on stackoverflow:

```js
const parse = require('csv-parse/lib/sync')
const fs = require('fs')
...

if (path.extname(cf_cover_dataset)=='.csv') {
  ...
  const records = parse(fs.readFileSync( COVER_file ), {...})
  const COVER = f(records);
  console.log("1. cover from CSV");
  main();
} else {
  COVER = JSON.parse(COVER_file)  // ... and WAY here
  console.log("1. cover from JSON");
  main();
}

function main() {  // step2, ugly but run in sequence 
   console.log("2. END!!");
}
```

**Comment by wdavidw** [comment]
`parse(...).on` There is no `on` function in the sample I sent you.
