### ISSUE TITLE
parser's end being triggered before last record

### ISSUE THREAD

**Issue by ashkank83** [adaltas/node-csv-parse#228]
Hi, I'm experiencing the same issue as [issue#59](https://github.com/adaltas/node-csv-parse/issues/59). below is my sample code and questions if you can kindly have a look. Thanks
```javascript
let parser = parse({
    delimiter,
    columns,
    cast: true,
    cast_date: true
  });
//---open the file to read records and process
createReadStream(fileAddress).pipe(parser);
parser.on("readable", async function() {
      //Q1
      let record;
      while ((record = parser.read())) //Q2
      {
      //some async function here (enriching data with data fetched from database)
      await enrichData(record);
      }
})
parser.on("end", async function() {
     //---if my file is one or two records it reaches "end" before the records are processed
})
```
**Question 1:** Is the end event called as soon as the last record is called? i.e. where I have marked in the code with Q1. Or does it wait for the function to finish and then triggers "end"?

**Question 2:** I have copied while((record = parser.read()) from your example, however don't understand the logic here! Is it ever possible that one readable event goes through this while more than once? 

Thanks

**Comment by wdavidw** [comment]
Question 1: the "end" events behavior is documented on the [Node.js website](https://nodejs.org/api/stream.html#stream_event_end)
Question 2: yes, it is possible for `parser.read` to return multiple chunks inside a 'readable' event, can't remember exactly how but maybe the `highWaterMark` option which affect the behavior of the buffer.

**Comment by wdavidw** [comment]
Relative to q1, end shall be called after Q2 for a synchronous function. Never tried for an async function passed to `on` but you could use [`stream-transform`](https://csv.js.org/transform/) for this. Once again, this is a Node.js behavior.

**Comment by ashkank83** [comment]
@wdavidw Thanks for the reply. 
You said "Relative to q1, end shall be called after Q2 for a synchronous function", so basically as soon as the last parser.read() is called the "end" will be triggered. Does this mean that the "End" event is always triggered before the last record is processed? 
Is there any other event or way that can guarantee all records have gone through the "readable" function before it gets triggered?

**Comment by ashkank83** [comment]
For anyone else out there, who might be having this same issue. I fixed the problem by wrapping the "readable" function inside a promise and when it reaches "End" I check if all promises are resolved. 
```javascript
let promiseArray = [];
let parser = parse({
    delimiter,
    columns,
    cast: true,
    cast_date: true
  });
//---open the file to read records and process
createReadStream(fileAddress).pipe(parser);
parser.on("readable", async function() {
promiseArray.push(new Promise((resolve,reject) => {
      let record;
      while ((record = parser.read()))
      {
      //some async function here (enriching data with data fetched from database)
      await enrichData(record);
      }
resolve(true);}));
})
parser.on("end", async function() {
await Promise.all(promiseArray);
     //---after all promises are resolved we can be sure that all records are consumed in "readable" event
})
```

**Comment by wdavidw** [comment]
This is not specific to the parser and more of a JS question. For the records, here's my recommendation:

```js
createReadStream(source)
.pipe(parse({
  ...options
}));
.pipe(transform(function(record, callback){
  enrichData(record).then(callback)
}))
.on("end", function() {
     console.log('End is called once all records are enriched')
})
```
