### ISSUE TITLE
Question: Limiting the Number of Rows Processed

### ISSUE THREAD

**Issue by brianhyder** [adaltas/node-csv-parse#232]
We are working on a UI where we upload the file then provide back the headers and up to the first 5 rows of data as "preview" for the user before they create a mapping.  

  I am curious if there is a way to limit essentially say, "start processing at row 0 and end at row 6".

Any help would be greatly appreciated.

**Comment by wdavidw** [comment]
yes, you can use the [`to` option](https://csv.js.org/parse/options/)

**Comment by brianhyder** [comment]
Apologies, I completely missed that.  Thank you.
