### ISSUE TITLE
Casting strings with e inside 

### ISSUE THREAD

**Issue by ashkank83** [adaltas/node-csv-parse#234]
I have a csv which looks something like below:

1004,1004601880DD,0,2019-02-14 16:55:20,
1004,1004601880DF,0,2019-02-14 16:55:34,
1004,1004601880**E0**,1,2019-02-14 16:55:00,
1004,1004601880**E1**,1,2019-02-14 16:50:57,
1004,1004601880**E2**,1,2019-02-14 16:55:21,
1004,1004601880**E4**,0,2019-02-14 16:55:35,

using
```
let parser = parse({
    delimiter: ',',
    columns: ['a','id','date'],
    cast: true,
    cast_date: true
  });
```

I was expecting for the cast option to consider my second column as a String, however it looks like for IDs ending with Ex (x being a number), it considers them as the scientific presentation of the number and converts them to number like: 

1004,1004601880DD,0,2019-02-14 16:55:20,
1004,1004601880DF,0,2019-02-14 16:55:34,
1004,**1004601880**,1,2019-02-14 16:55:00,
1004,**10046018800**,1,2019-02-14 16:50:57,
1004,**100460188000**,1,2019-02-14 16:55:21,
1004,1**0046018800000**,0,2019-02-14 16:55:35,

Is Casting working line by line? or does it consider other lines as well when casting the columns? 
If it's line by line, which makes sense for performance purposes, is there anyway that I can tell the parser to consider my second column as String and not int? Thanks

**Comment by wdavidw** [comment]
Note, your first 2 options are not valid.

Casting is working at the field level. For greater control, you can define cast as a function. see the [documentation](https://csv.js.org/parse/options/cast/). You can use the `context.index` property to cast your field to your wish.

**Comment by ashkank83** [comment]
Thanks, Fixed the first 2 options to avoid confusion if anyone else reads the comments! 

I started using casting functions and it's working great. However, when adding a function for cast, it looks like the **cast_date** is being ignored. Is this by design or am I missing something? 

Also as feature request, Does it make sense to accept Columns as an array of 
```
[{
Header, 
Type:  [Number, String, Date,... and Auto or undefined which is equal to Cast === True in current version]
Cast [Optional] (if available overrides the Type)
}]

I think the above will give more flexibility to developers to mix the auto cast and more fine tuned Cast functions. What do you think?

I'm very new to JS development but happy to help with development of this feature if you think it makes sense!

**Comment by wdavidw** [comment]
It is by design. First, I've never been to proud of the `cast_date` option. Second, when providing a `cast` function, it cast all field and it would be confusing not to do so or use it conjointly with `cast_date`. Can we close the issue ?

**Comment by ashkank83** [comment]
Sure, Thanks for your help. great work
