### ISSUE TITLE
Fails with cryptic error on UTF-8 CSV with BOM

### ISSUE THREAD

**Issue by Phrogz** [adaltas/node-csv-parse#236]
1. Save a CSV file as UTF-8 with BOM
2. Read in Node and pass to CSV Parse

```js
const csvparse = require('csv-parse/lib/sync')
const csvWithBOM = '\ufeff"first_name","last_name"\n"Gavin","Kistner"\n"Imelda","Marcos"'
console.log(csvparse(csvWithBOM, {columns:true}))
```

**EXPECTED**: CSV is parsed, or at least a reasonable error is displayed
```
[ { first_name: 'Gavin', last_name: 'Kistner' },
  { first_name: 'Imelda', last_name: 'Marcos' } ]
```

**ACTUAL**: Error message raised that does not give user any idea what's wrong, given that the BOM is an invisible character:
```
/tmp/test/node_modules/csv-parse/lib/sync.js:18
  if(err1 !== undefined) throw err1
                         ^

Error: Invalid opening quote at line 1
    at Parser.__error (/tmp/test/node_modules/csv-parse/lib/index.js:816:17)
    at Parser.__parse (/tmp/test/node_modules/csv-parse/lib/index.js:450:34)
    at module.exports (/tmp/test/node_modules/csv-parse/lib/sync.js:17:23)
    at Object.<anonymous> (/tmp/test/tmp.js:3:13)
```

**WORKAROUND**: Be sure to strip any potential BOM before passing CSV to the parser, e.g.
`myCSV = myCSV.replace(/^\ufeff/, '')`

**Comment by wdavidw** [comment]
I am kind of hesitating whether handling UTF BOM is part of the scope of a parser. I cant make my decision about it.

**Comment by Phrogz** [comment]
@wdavidw I absolutely know what you mean. I was on the fence about reporting this error for the same reason. If Node provided a non-hacky way to strip the BOM during file reading I would definitely say that this was not the parser's responsibility. I'd probably accept closing this bug by putting a documentation note up and then letting this report live to tie the error message to the root cause. Even better would be a better error message, e.g. "Invalid unquoted character on line 1, position 1". But it would be nicer if it "just worked".

Are there a slew of similar, likely, "bad-encoding" problems? If so, then this should not be handled by the parser. If not, maybe it's worth silently handling to save those unfamiliar with problems like these the headaches.

**Comment by wdavidw** [comment]
I am very surprised there are not so many reports about this issue after so many years. It was supported [at some point](https://github.com/adaltas/node-csv-parse/commit/53b44ed0e807dda9022fc1db043a9ca71eaf8edd).
