### ISSUE TITLE
Version 4.4.2 breaks with "Cannot find module 'csv-parse/lib'"

### ISSUE THREAD

**Issue by mmammel** [adaltas/node-csv-parse#240]
My project is bringing in csv-parse via some restify packages, and ~15 minutes ago I began to get the following error:

node_1  | internal/modules/cjs/loader.js:584
node_1  |     throw err;
node_1  |     ^
node_1  |
node_1  | Error: Cannot find module 'csv-parse/lib'
node_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
node_1  |     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
node_1  |     at Module.require (internal/modules/cjs/loader.js:637:17)
node_1  |     at require (internal/modules/cjs/helpers.js:22:18)
node_1  |     at Object.<anonymous> (/home/node/node_modules/csv/lib/index.js:6:10)
node_1  |     at Module._compile (internal/modules/cjs/loader.js:701:30)
node_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
node_1  |     at Module.load (internal/modules/cjs/loader.js:600:32)
node_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
node_1  |     at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by wdavidw** [comment]
I've seen it once recently so I think I know what it is. Could you try now with version 4.4.3.

**Comment by orangejulius** [comment]
I'm seeing this too, and 4.4.3 fixes this for me, thanks for the quick turnaround :) ❤️

**Comment by wdavidw** [comment]
No worries, it seems like the files field in the packages.json no longer accept path starting with "./".

**Comment by mmammel** [comment]
Confirmed fixed - thank you!

**Comment by bessiambre** [comment]
This seems to not be fixed when using 'npm install -g'. I worked around by not using the global flag but I thought I'd mention it.

To reproduce:

    npm install -g csv-parse

    <run file containing 'const parse = require('csv-parse/lib/sync');'>

Error: Cannot find module 'csv-parse/lib/sync

    npm install csv-parse

now file runs ok.

**Comment by wdavidw** [comment]
Are you sure this is related to the package.json `file` field? I am not sure requiring global module is supported, see this [stackoverflow thread](https://stackoverflow.com/questions/7970793/how-do-i-import-global-modules-in-node-i-get-error-cannot-find-module-module).
