### ISSUE TITLE
empty first line

### ISSUE THREAD

**Issue by SET001** [adaltas/node-csv-parse#241]
In case document (for any reason) has few empty lines on top of it, they will not be ignored neither with `skip_empty_lines`, not with `skip_lines_with_empty_values` and headers will be parsed.
I suppose `skip_empty_lines` should lead `columns: true,` to take headers not from first line, but from first not-empty line.

**Comment by wdavidw** [comment]
Could you please provide a unit test or a minimal sample illustrating the case, thank you.

**Comment by SET001** [comment]
mocha test in es6:

```
import { assert } from 'chai'
import * as csvParse from 'csv-parse/lib/sync'
  describe('csvParse', () => {
    it.only('should skip empty line', () => {
      const file = `,,\nheader1,header2,header3\nvalue11,value12,value13\nvalue21,value22,value23`
      const res = csvParse(file, {
        columns: true,
        trim: true,
        delimiter: ',',
        skip_empty_lines: true,
        skip_lines_with_empty_values: true,
      })
      assert.isDefined(res[0].header1)
      assert.isDefined(res[0].header2)
      assert.isDefined(res[0].header3)
    })
  })
```

**Comment by wdavidw** [comment]
Thank you, I'll look into how to implement this new feature
