### ISSUE TITLE
Double quotes at the end throws error in version 2.5.0 and not in 4.4.3

### ISSUE THREAD

**Issue by DineshKumaraguru-Payoda** [adaltas/node-csv-parse#245]
In version, 2.5.0 double quotes only at the end of the value throw an error whereas in version 4.4.3 it accepts.

I have used **relax: true** for accepting double quotes in 4.4.3.

"sample text - Throws Error 
sample text" - Accepted with the trailing quotes.

Is there any way to get an error for the above text.

**Comment by wdavidw** [comment]
Could you clarify to make sure I understand:

```js
parse('a,b\nc,"sth', {...options}, function(err, data){
  // what to we get, what do you expect
})
```

and 

```js
parse('a,b\nc,sth"', {...options}, function(err, data){
  // what to we get, what do you expect
})
```

**Comment by DineshKumaraguru-Payoda** [comment]
Hi,

parse('a,b\nc,"sth', {columns, trim: true, relax: true,
relax_column_count: true, escape: '"', skip_empty_lines: true, },
(err, data) => {

console.log('Error', err, 'Data', data);

});

*what to we get:*

Error: Error: Invalid Closing Quote: quote is not closed at line 2

Data: undefined

*Expected Output:* Same as what we get.

parse('a,b\nc,sth"', {columns, trim: true, relax: true,
relax_column_count: true, escape: '"', skip_empty_lines: true, },
(err, data) => {

console.log('Error', err, 'Data', data);

});

*what to we get:*

Error: undefined

Data: [ { column1: 'a', column2: 'b' }, { column1: 'c', column2: *'sth"'* } ]

*Expected Output: *

Error: Error: Invalid Opening/Closing Quote: quote is not closed at line 2

Data: undefined


Regards

Dinesh Kumaraguru.

**Comment by wdavidw** [comment]
Please reformat, for example use triple ` for code, remove all irrelevant options

**Comment by mkovac-conductive** [comment]
Same here.

CSV file:
"Name","Age"
""Bob","23"

Result: 
[ { Name: '""Bob"', Age: '23' } ]

CSV file:
"Name","Age"
"Bob"","23"

Error:
'Invalid Record Length: header length is 2, got 1 on line 2'
Expected Result: 
[ { Name: '"Bob""', Age: '23' } ]


Config:
    const parser = parse({
      delimiter: `,`,
      relax: true,
      columns: true
    });

**Comment by wdavidw** [comment]
thanks @mkovac-conductive, this makes it clearer. I am not sure how/whether we shall handle such a case.

**Comment by wdavidw** [comment]
Closing, feel free to re-open to engage further discussions
