### ISSUE TITLE
there is a problem in cast context.column

### ISSUE THREAD

**Issue by Manjiz** [adaltas/node-csv-parse#249]
```js
columns: true,
cast: (value, context) => {
  // page_id 8
  console.log(context.column, context.column.length)
}
```

there is a sightless char before 'p'

**Comment by Manjiz** [comment]
Important hint: `page_id` is the most firstly word in csv file

**Comment by wdavidw** [comment]
Could you provide a fully functional and reproducible example because I don't understand your issue?
