### ISSUE TITLE
Sync parse mishandling first column on UTF16LE content

### ISSUE THREAD

**Issue by rotero** [adaltas/node-csv-parse#250]
Parsing of UTF16LE content leads to first column (property) ending up in quotes:

```
const parse = require('csv-parse/lib/sync');
let contents = fs.readFileSync(fname, 'utf16le'); 
let res=parse(contents, {quote:false,columns: true, delimiter:'\t',trim:true}); 
```

input (example -pseudo code):
col1\tcol2\tcol3
val1\tval2\tval3

output in version 2.4.0 - correct as expected:
```
[
{
col1:val1,
col2:val2,
col3:val3
}
]
```

output in version 4.4.5 - WRONG: 
```
[
{
'col1':val1,
col2:val2,
col3:val3
}
]
```

Please note that the output in latest version is ALWAYS with quotes for the first column.

**Comment by wdavidw** [comment]
I dont have much time at the moment so I will appreciate your help. You could prepare a unit test (or just a sample script) which write a file with the UTF16LE encoding and some minimalist content and assert the expected result.

**Comment by rotero** [comment]
here you go: 
https://repl.it/repls/CornsilkStaleRam <https://repl.it/repls/CornsilkStaleRam>

use old npm package (v 2.40 works for me but didn’t try newer ones)

**Comment by wdavidw** [comment]
I believe that I found the reason. In version 2, the BOM was automatically detected, while in the current version, according to the doc and the REPL you submitted above, you must explicitly pass the bom option as `true`. Closing but feel free to re-open if needed.
