### ISSUE TITLE
Drop header row if columns are defined

### ISSUE THREAD

**Issue by sjl2** [adaltas/node-csv-parse#251]
We're currently parsing an array using the `columns` option. However, we want our input to be able handle CSVs where the header is provided. Right now, it parses any provided header row as if it matched the `columns` array defined.

Ideally, if a header row is found that matches the `columns` option, the parser would drop it. Right now, we have to use a transformer to drop if present, when really, this scope seems more fitting for the parser logic. 

Has anyone else run into a similar issue with parsing CSVs with and without headers? Is there a better work-around than using a transformer? Unfortunately, due to the CSV sources, we cannot guarantee consistent CSV input with/without headers without extra burden to the users. 

```js
const csvHeader = 'id\nobj_1\nobj_2'; // header included
//const csvNoHeader = 'obj_1\nobj_2'; // no header

const passThrough = new Stream.PassThrough();
passThrough.write(csvHeader);
passThrough.end();

const idParser = CSV.parse({
  columns: ['id'],
  trim: true
});

passThrough.pipe(idParser); // outputs [{ id: 'id' }, { id: 'obj_1' }, { id: 'obj_2' }] 

// requires us to have to filter out `{ id: 'id' }` in future transformers
```

**Comment by wdavidw** [comment]
You could use the `from` option, no ?

**Comment by sjl2** [comment]
> You could use the `from` option or set column to `true`, no ?

We can do that to handle this case, but then it won't parse CSVs without the header. Ideally, we're looking for the ability to configure it to parse a CSV with and without the header when it's specified. 

Otherwise, we have to read the first line, and determine how to parse it (set columns to names or `true`).

**Comment by wdavidw** [comment]
You can also achieve this behavior with the `transform` which was recently introduced. Did you check this opportunity ?

**Comment by sjl2** [comment]
> You can also achieve this behavior with the `transform` which was recently introduced. Did you check this opportunity ?

Yep! That's actually the work around we currently have in place to essentially skip a line if it's identical to the column expected (`id`) in our case. 

```js
const transform = (row, callback) => {
  if (row.id === 'id') {
    return callback(null, row);
  }

  // remaining side-effect logic
};

const transformer = CSV.transform(transform, options); 
```

So yes, no rush since there is a valid work-around. Mostly just highlighting that when columns are known, it's nice to be able to allow the header on the input file (ignoring it when present).

**Comment by wdavidw** [comment]
Not much activity, closing.
