### ISSUE TITLE
I would like to log invalid lines, but don't stop parsing

### ISSUE THREAD

**Issue by Ginden** [adaltas/node-csv-parse#252]
We parse CSV files from external supplier. These files often contain errors and we would like to report them to that supplier.

Each line is independent of others, so we don't need to stop parsing if one lines contain an error.

**Comment by wdavidw** [comment]
Have you tried [the skip_lines_with_error option](https://csv.js.org/parse/options/skip_lines_with_error/). It emits a `skip` event with the error as first argument.

**Comment by Ginden** [comment]
Oh, I have missed part about `'skip'` event, this solves my issue!
