### ISSUE TITLE
IE or Edge error 

### ISSUE THREAD

**Issue by miaovictor** [adaltas/node-csv-parse#253]
class Parser extends Transform，but Transform is import as a const variable，in Parser‘s constructor function:
`super({ ...{ readableObjectMode: true }, ...opts })`
this code is change the const variable, IE and Edge browser not work！

**Comment by wdavidw** [comment]
Not sure I understand the issue. In case this is related to browser support, you should use 'csv-parse/lib/es5'. Please close if this fix your issue or elaborate a bit more.

**Comment by wdavidw** [comment]
No answer, closing.
