### ISSUE TITLE
csv-parse 4.6.1 reports an improper error

### ISSUE THREAD

**Issue by snakamura** [adaltas/node-csv-parse#259]
By running this code snippet, csv-parse@4.5.0 reports `Invalid Record Length: header length is 3, got 4 on line 3`, but csv-parse@4.6.1 reports `TypeError: Cannot read property 'name' of undefined`.

```
const csv = require('csv-parse');

const data =
    '"Column1","Column2","Column3"\n' +
    '"data11","data12","data13"\n' +
    '"data21","data22","data23",\n' +
    '"data31","data32",';

csv(data, {
    columns: true
}, error => {
    console.log(error);
});
```

**Comment by wdavidw** [comment]
Thank you for reporting, version 4.6.2 fix the issue.
