### ISSUE TITLE
Wrong index bound check in __context()

### ISSUE THREAD

**Issue by bolt-juri-gavshin** [adaltas/node-csv-parse#260]
https://github.com/adaltas/node-csv-parse/blob/f13485478b1885276d984705a932bf69730f897b/lib/index.js#L893
```
columns.length >= this.state.record.length ?
          columns[this.state.record.length].name :
          null
```
should be replaced with 
```
columns.length > this.state.record.length ?
          columns[this.state.record.length].name :
          null
```

**Comment by wdavidw** [comment]
do you have a sample with you so that I can move on quickly by integrating it into our tests?

**Comment by bolt-juri-gavshin** [comment]
I'm afraid the data is from our private repo.
But looking at the code, you just need a document which has more columns than there are in the options object
