### ISSUE TITLE
Remove column by Cast option

### ISSUE THREAD

**Issue by rubyzhao** [adaltas/node-csv-parse#266]
**How to remove the specified columns in parse?**

As the example at https://csv.js.org/parse/options/cast/.
I want remove first column: 2000-01-01 and 2050-11-27

**Describe the solution you'd like**
If return null or undefined as below, the first column and ',' will be removed.
```
if(context.index === 0){
      return null
}
```
Then the following should pass the test.
```
assert.deepEqual(records, [
  [ {
    column: 1, empty_lines: 0, header: false, index: 1,
    invalid_field_length: 0, lines: 1, quoting: false, records: 0
  } ],
  [ {
    column: 1, empty_lines: 0, header: false, index: 1,
    invalid_field_length: 0, lines: 2, quoting: false, records: 1
  } ]
])

```

**Comment by wdavidw** [comment]
The new [`on_record`](https://csv.js.org/parse/options/on_record/) option introduced with version 4.7.0 shall help you achieve what you need.

**Comment by rubyzhao** [comment]
Thanks for that. Would you please publish the latest package to npm? I just tested the on_record examples at https://csv.js.org/parse/options/on_record/. Both failed.

**Comment by wdavidw** [comment]
I just checked, version 4.7 of csv-parse is published. Maybe because your are using the csv package, I will publish an update on that one now.

**Comment by rubyzhao** [comment]
Great. Well done.
