### ISSUE TITLE
on_record option is not working (documentation does not match with the current version)

### ISSUE THREAD

**Issue by cibergarri** [adaltas/node-csv-parse#267]
**Describe the bug**
on_record option is not taken into account

**To Reproduce**
`parse('test', { on_record: (record) => { console.log('record', record); } }, (err, output) => { console.log('end parse') });`
does not log anything.

**Additional context**
The latest release was 22 days ago but the commit from @wdavidw was only 3 days ago. 
Moreover, if you navigate into the files installed with the package, you cannot find a mention of the "on_record" option.
Therefore I guess there has not been release for this feature yet.

Thank you in advance!

**Comment by wdavidw** [comment]
It was just released

**Comment by cibergarri** [comment]
Thanks @wdavidw !!
