### ISSUE TITLE
TypeError: "Error.captureStackTrace is not a function" in firefox

### ISSUE THREAD

**Issue by Octavic** [adaltas/node-csv-parse#270]
**Describe the bug**
Getting a TypeError: "Error.captureStackTrace is not a function" in Firefox when trying to parse a malformed CSV file
Using version 4.8.2

**To Reproduce**
Create a simple React application and include the following code
```const parse = require('csv-parse')
const data = "A,B\ntest"
parse(data, {}, (err, output) => {
  console.log(err);
  console.log(output);
});
```

Running the application generates the following Error:
```TypeError: Error.captureStackTrace is not a function
CsvError

  1155 | constructor(code, message, ...contexts) {
  1156 |   if (Array.isArray(message)) message = message.join(' ');
  1157 |   super(message);
> 1158 |   Error.captureStackTrace(this, CsvError);
       | ^  1159 |   this.code = code;
  1160 | 
  1161 |   for (const context of contexts) {
```

**Additional context**
Verified in Firefox 71.0(32-bit)

**Comment by wdavidw** [comment]
It shall be fixed with commit f1081345e7376535665e9f56c913df50b9abb76d, thank you
