### ISSUE TITLE
Missing type declarations for parse function

### ISSUE THREAD

**Issue by carnun** [adaltas/node-csv-parse#272]
**Describe the bug**
A per the csv-parse documentation I specify the delimiters as an option with sync.d.ts being the only typedefs available this is no longer valid. I.e. the following code used to work fine
```
// example.ts
import parse from 'csv-parse'
const parser = parse({
  delimiter: ':',
  relax_column_count: true
})
```
However this now gives a compilation error of
```
Argument of type '{ delimiter: string; relax_column_count: boolean; }' is not assignable to parameter of type 'string | Buffer'
```

**To Reproduce**
Install the latest version of csv-parse and build a project using the code above (`example.ts`).

**Additional context**
I'm not exactly sure why `./lib/sync.d.ts` was made the `types` definition in `package.json` in `4.8.4`. I would rather expect `./lib/index.d.ts` to be made the `types` definition.

**Comment by wdavidw** [comment]
I made a mistake earlier in the last release, could you pull version 4.8.5, it shall fix it.
