### ISSUE TITLE
throwing inappropriate exception message if a cell has unclosed double quote

### ISSUE THREAD

**Issue by madhav-vl** [adaltas/node-csv-parse#273]
**Describe bug**
throwing inappropriate exception message if a cell has unclosed double quote

I have installed csv-parse version: 4.8.5. 
If importing a csv which has unclosed double quote in any cell, throwing below exception
**code**:"CSV_INVALID_CLOSING_QUOTE"
**column**:"column_name"
**message**:"Invalid Closing Quote: got "O" at line 5 instead of delimiter, row delimiter, trimable character (if activated) or comment"

**To Reproduce**
![image](https://user-images.githubusercontent.com/60141341/74837959-9e7d8b80-5348-11ea-8c16-75c43727b27c.png)
Hope above attachment would help in reproducing the issue. 2nd data row 6th column has un-closed text ("def).
The below line of code throwing an exception.
let parser = CSVParse(file.buffer, options);

**Comment by wdavidw** [comment]
Could you please provide a sample.

**Comment by wdavidw** [comment]
See my comment for #274, feel free to re-open with a sample

**Comment by madhav-vl** [comment]
Hi @wdavidw, csv attached here for your reference.
[upload_file.zip](https://github.com/adaltas/node-csv-parse/files/4248042/upload_file.zip)

**Comment by wdavidw** [comment]
Same comment as for #277. Please, provide a minimal example with a minimal dataset, no zip file.
