### ISSUE TITLE
Unable to read csv if a row has empty columns

### ISSUE THREAD

**Issue by madhav-vl** [adaltas/node-csv-parse#274]
**Describe the bug**

I have installed csv-parse version: 4.8.5
Unable to read csv if a row has empty columns, throwing below exception
**CODE:** "CSV_RECORD_DONT_MATCH_COLUMNS_LENGTH"
**message:** "Invalid Record Length: columns length is 12, got 10 on line 4"

**To Reproduce**
Upload a csv which has 12 columns. Provide data for each cell in first 2 data rows, and leave last two columns of last (3rd) row empty. Hope below attachment would help in reproduce the issue.
![image](https://user-images.githubusercontent.com/60141341/74839175-d685ce00-534a-11ea-888b-5339d63c4598.png)

**Additional context**
N/A

**Comment by wdavidw** [comment]
Please provide your sample as text instead of an image if you expect some help.
