### ISSUE TITLE
Error handling within on_record callback

### ISSUE THREAD

**Issue by robertpitt** [adaltas/node-csv-parse#275]
**Describe the bug**
Version: 4.8.5

Errors throwing within the on_record callback are not effected by the `skip_lines_with_error` option, this is making it difficult for me to utilise the on_record feature as an uncaught exception will fail the entire file. 

**To Reproduce**
Playground: https://repl.it/@RobertPitt/CSV-Paese

```ts
const parse = require('csv-parse')
const assert = require('assert')

const data = `a,b,c,d
a,b,c,-` // bad data row

const on_record = ([a, b, c, d]) => {
  if(d !== "d") throw new TypeError('Something went wrong')
  return [a, b, c, d]
}

const parser = parse(data, {
  on_record,
  delimiter: ',',
  skip_lines_with_error: true,
})

console.log(parser.read())
console.log(parser.read())
```

**Result**
Exception is thrown within the on_record call, error breaks stream and throws a global exception which results in a crash.

**Expected Result**
Exception to be caught and emitted as a `skip` event with a `CSVError`.

**Additional context**

My plan is to use the on_record handler to transform the parsed CSV data before it gets emitted out as a data event, however my concern is that if an unexpected error occurs within the on_record call this will result in a crash and  loss of the entire file/stream.

**Comment by wdavidw** [comment]
Current behavior is to interprent the error of `skip_lines_with_error` as a parsing error, an invalid CSV data, not a user thrown error. If you wish to skip this line, return null instead of throwing an error.

**Comment by wdavidw** [comment]
Errors are now caught and correctly handled. Note, the original error is sent and not a CSVError as you requested. A new patch version is available.

**Comment by robertpitt** [comment]
Hey @wdavidw,

Thanks for the super quick change for this, however I have just tweaked the playground I setup to run `v4.8.6` but still seeing exceptions occurring and not going the skip handler

```
const { PassThrough } = require('stream')
const parse = require('csv-parse')
const assert = require('assert')

const on_record = ([a, b, c, d]) => {
  if(d !== "d") throw new TypeError('Something went wrong')
  return [a, b, c, d]
}

const parser = parse("a,b,c,d\na,b,c,-", {
  on_record,
  delimiter: ',',
  skip_lines_with_error: true,
})

parser.on('skip', () => console.log('Skipped'))
parser.on('error', () => console.log('Error'))
parser.on('data', (d) => console.log('Data', d))
parser.on('end', () => console.log('End'))
```

Playground: https://repl.it/@RobertPitt/CSV-Paese
