### ISSUE TITLE
Unable to read csv if a row has empty columns

### ISSUE THREAD

**Issue by madhav-vl** [adaltas/node-csv-parse#276]
**Describe the bug**
I have installed csv-parse version: 4.8.5
Unable to read csv if a row has empty columns, throwing below exception
CODE: "CSV_RECORD_DONT_MATCH_COLUMNS_LENGTH"
message: "Invalid Record Length: columns length is 12, got 10 on line 4"

**To Reproduce**
Upload a csv which has 12 columns. Provide data for each cell in first 2 data rows, and leave last two columns of last (3rd) row empty. Hope below attachment would help in reproduce the issue.
[upload_file_col.zip](https://github.com/adaltas/node-csv-parse/files/4248049/upload_file_col.zip)

**Comment by wdavidw** [comment]
Same comment as #277, please, provide a minimal example with a minimal dataset, no zip file.

**Comment by madhav-vl** [comment]
Hi @wdavidw
Please find the details below to reproduce the issue

**Code that throwing an exception**
/* csv upload. */
router.post('/import', upload.single('csv'), upload.single('csv'), function (req, res, next) {
try {
console.log('importing document..')
const buffer = req.file.buffer;
const options = {
columns: true
};
let parser = CSVParse(buffer, options);
} catch (err) {
//throw err;
res.status(500).send({
errInfo: err,
mssage: err.message
});
}
});

**Exception message**
![image](https://user-images.githubusercontent.com/60141341/75322457-cadd5e80-5898-11ea-8025-8957d6ff7a06.png)

Find the attachment which has example application and a csv file uploaded.
[req_data.zip](https://github.com/adaltas/node-csv-parse/files/4254024/req_data.zip)

I hope this information helps you in reproducing the issue

**Comment by wdavidw** [comment]
See my comment in #277

**Comment by jacobq** [comment]
@madhav-vl have you read about the [`relax_column_count` option](https://csv.js.org/parse/options/relax_column_count/)?

**Comment by wdavidw** [comment]
Closing, no answer being provided to the last question.
