### ISSUE TITLE
throwing inappropriate exception message if a cell has unclosed double quote

### ISSUE THREAD

**Issue by madhav-vl** [adaltas/node-csv-parse#277]
**Describe the bug**
throwing an inappropriate exception message if a cell has unclosed double quote

installed csv-parse version: 4.8.5.
If importing a csv which has unclosed double quote in any cell, throwing below exception
code:"CSV_INVALID_CLOSING_QUOTE"
column:"column_name"
message:"Invalid Closing Quote: got "O" at line 5 instead of delimiter, row delimiter, trimable character (if activated) or comment"

**To Reproduce**
The csv file attached for your reference, hope will help you in udderstanding and reproducing the issue. 2nd data row 6th column has un-closed text ("def). [upload_file.zip](https://github.com/adaltas/node-csv-parse/files/4248053/upload_file.zip)

The below line of code throwing an exception.
let parser = CSVParse(file.buffer, options);

**Comment by wdavidw** [comment]
Please, provide a minimal example with a minimal dataset, no zip file.

**Comment by madhav-vl** [comment]
Hi @wdavidw 
Please find the details below to reproduce the issue

**Code that throwing an exception**
/* csv upload. */
router.post('/import', upload.single('csv'), upload.single('csv'), function (req, res, next) {
  try {
    console.log('importing document..')
    const buffer = req.file.buffer;
    const options = {
      columns: true
    };
    let parser = CSVParse(buffer, options);
  } catch (err) {
    //throw err;
    res.status(500).send({
      errInfo: err,
      mssage: err.message
    });
  }
});


**Exception message**
![image](https://user-images.githubusercontent.com/60141341/75321949-ded49080-5897-11ea-8388-0b40ae1d4013.png)


Find the attachment which has example application and a csv file uploaded.
[req_data.zip](https://github.com/adaltas/node-csv-parse/files/4253993/req_data.zip)

I hope this information helps you in reproducing the issue

**Comment by madhav-vl** [comment]
Hi @wdavidw
Please find the details below to reproduce the issue

**Code that throwing an exception**
/* csv upload. */
router.post('/import', upload.single('csv'), upload.single('csv'), function (req, res, next) {
try {
console.log('importing document..')
const buffer = req.file.buffer;
const options = {
columns: true
};
let parser = CSVParse(buffer, options);
} catch (err) {
//throw err;
res.status(500).send({
errInfo: err,
mssage: err.message
});
}
});

**Exception message**
![image](https://user-images.githubusercontent.com/60141341/75322678-46d7a680-5899-11ea-98f0-ddce6e01ef51.png)

Find the attachment which has example application and a csv file uploaded.
[req_data_e.zip](https://github.com/adaltas/node-csv-parse/files/4254062/req_data_e.zip)

I hope this information helps you in reproducing the issue.

**Comment by wdavidw** [comment]
Please, not zip file, and a clean/formatted code will help. Take a look at the sample and test directories. This is what I expect, for example:

```js
const parse = require('..')
const assert = require('assert')

parse(`
"first","last"
"Paul-Émile","Victor"
`.trim(), {
  max_record_size: 10
}, function(err, records){
  assert.ok(
    /Max Record Size/.test(err.message)
  )
})
```

**Comment by wdavidw** [comment]
See my comment in #277

**Comment by madhav-vl** [comment]
router.post('/import', upload.single('csv'), upload.single('csv'), function (req, res, next) {
  try {
    console.log('importing document..')
    const buffer = req.file.buffer;
    const options = {
      columns: true
    };

    let parser = CSVParse(buffer, options);
  } catch (err) {
    //throw err;
    res.status(500).send({
      errInfo: err,
      mssage: err.message
    });
  }
});

**Comment by birhoff** [comment]
Hello, my example
```js
const { promisify } = require('util');
const parse = promisify(require('csv-parse'));

const csvStr = 'Имя котика;Цвет котика\n' + '"Sir Pawncelot" ;"red"';

(async function csv() {
    return await parse(csvStr.trim(), {
        delimiter: ';',
    });
})();

```

**Comment by wdavidw** [comment]
Thank you @birhoff, having a sample helps a lot. There is no need to use promise in your sample. It is much simpler using sync:

```js
const parse = require('csv-parse/lib/sync');
parse('a1;a1\n"b1" ;"b2"';, {
    delimiter: ';',
});
```

Also, the input could be shorted and there is no need to specify a quote option:

```js
const parse = require('csv-parse/lib/sync');
parse('a1,a1\n"b1" ,"b2"', {});
```

In this data set, the closing quote character on the second line is a "space". The error code and message are appropriate: "Invalid Closing Quote: got " " at line 2". You can use the `trim` option if you wish to accept space after your closing quote:

```js
const parse = require('./lib/sync');
console.log(
  parse('a1,a1\n"b1" ,"b2"', {trim: true})
);
```
