### ISSUE TITLE
Error handling within on_record while using stream api

### ISSUE THREAD

**Issue by robertpitt** [adaltas/node-csv-parse#278]
Describe the bug
Version: 4.8.6

I previously opened #275 in regards to errors being thrown within the on_record callback were not effected by the `skip_lines_with_error` option, although the issue was closed and resolved I think that the issue still persists (specifically under streaming scenarios)

**To Reproduce**
Playground: https://repl.it/@RobertPitt/CSV-Paese-1

```
const parse = require('csv-parse') // 4.8.6

const on_record = ([a, b], { lines }) => {
  if(lines === 2)
    throw new TypeError('Something went wrong')
  return [a, b]
}

const parser = parse("a,b\nc,d\ne,f", {
  on_record,
  skip_lines_with_error: true,
})

// Under this configuration, no events actually emit and global exception is throw.
parser.on('skip', () => console.log('Skipped'))
parser.on('error', () => console.log('Error'))
parser.on('data', (d) => console.log('Data', d))
parser.on('end', () => console.log('End'))
parser.end()
```
**Additional context**

See issue: #275

**Comment by wdavidw** [comment]
This was due to a bug not related to `on_record`. Fixed now. Notes about your code: you shall not call `end` since you are passing a string and not using the writable stream api; `on('data',..)` shall be `on('readable',..)`
