### ISSUE TITLE
Return non utf-8 responce

### ISSUE THREAD

**Issue by Randima-Lahiru** [adaltas/node-csv-parse#279]
In my case I try to read csv file which is available on google cloud storage.
This is my code:

```
const file= storage.bucket('my-bucket').file('file.csv')

file.createReadStream({encoding: 'utf8'})
    .on('error', (err) => {
      console.log(err)
    })
    .pipe(csv())
    .on('data', (row) => {
        console.log(row);
    }) 
    .on('end', (end) => {
        console.log(end)
    })

  });
```
output: 

> '\u0000D\u0000a\u0000i\u0000l\u0000y\u0000 \u0000D\u0000e\u0000v\u0000i\u0000c\u0000e\u0000 \u0000I\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000s\u0000': '\u00005\u00000\u0000',

Any idea what may be going wrong here?

**Comment by wdavidw** [comment]
Your issue is not related to the parser but probably with your usage of Google storage. Try it with a local file, it work:

```js
const fs = require('fs')
const parse = require('.')

fs.createReadStream('test.csv', {encoding: 'utf8'})
.on('error', (err) => {
  console.log(err)
})
.pipe(parse())
.on('data', (row) => {
    console.log(row);
}) 
.on('end', (end) => {
    console.log(end)
})
```
