### ISSUE TITLE
setImmediate is undefined

### ISSUE THREAD

**Issue by kahurangitama** [adaltas/node-csv-parse#280]
I use csv@5.3.1 and got strange error on this line:
```
index.js:1039 Uncaught ReferenceError: setImmediate is not defined
    at Object._ [as parse] (index.js:1039)
    at FileReader.t.onload (ListEdit.tsx:139)
```
If you mean window.setImmediate it's not recommended using for production.
IDK, how to reproduce, it happens randomly, tested on Chrome, Safari, etc. 
On Chrome, sometimes it not happens, on Safari, it happens every time.

**Comment by wdavidw** [comment]
`setImmediate` is for Node.js, I'll can't think of a clean way to handle this inside web browser

**Comment by wdavidw** [comment]
I have just release a quick fix with version 4.8.8

**Comment by kahurangitama** [comment]
So I couldn't use the this npm on frontend side?

**Comment by wdavidw** [comment]
You can with version 4.8.8. Previous version introduced a regression.

**Comment by kahurangitama** [comment]
Nice! Seems it works now! 👍 🥇
