### ISSUE TITLE
Readable getting called multiple times

### ISSUE THREAD

**Issue by saharshjain** [adaltas/node-csv-parse#281]
**Description**

I am using CSV-Parse from quite a long time and amazed by it performance. Also I am publishing individual row to RabbitMQ queues. On readable I am trying to call another API to update total rows in DB. I could see that there are multiple calls to the function that executes after readable.

I am unable to understand why is there multiple calls to readable event.
**STR**
My code - 
```

async processFile(filename) {
    let cnt = 0;
    let index = null;
    let rowCounter = 0;
    const handler = (resolve, reject) => {
      const parser = CsvParser({
          delimiter: ',',
        })
        .on('readable', () => {
          let row;
          this.meta.totalRows = (parser.info.records - 1);
          //update imports metdata first then proceed for row publishing
          this.updateRows(filename)
            .then((response) => {
              while (row = parser.read()) {
                if (cnt++ === 0) {
                  index = row;
                  continue;
                }
                let messageObject = {
                  customFieldsMap: this.customFieldsMap,
                  importAttributes: this.jc.attrs,
                  importColumnData: row,
                  rowCount: cnt,
                  importColumnList: index,
                  authToken: this.token
                }
                console.log("Publishing row no. " + messageObject.rowCount);
                this.rowPublishChannel.sendToQueue(RowPublishQueue, new Buffer.from(JSON.stringify(messageObject)))
              }
            })
        })
        .on('end', () => {
          console.log("File consumed!");
          this.rowPublishChannel.close().then((response) => {
            console.log("Closed RabbitMQ  publish channel.");
          });
        })
        .on('error', reject);
      fs.createReadStream(filename).pipe(parser);
    };
    await new Promise(handler);
  }


  async updateRows(filename) {
    return await this.setStatus("queued");
  }


  async setStatus(status) {
    const dto = await this.apiService.imports.get(this.data.orgId, this.data.importId);
    dto.status = status;
    dto.metadata = this.meta;
    return this.apiService.imports.update(this.data.orgId, dto);
  }


```

processFile is called when I receive a message then I download a file and stat reading it. I wanted to execute the setStatus before I start reading it. But with above code my setStatus function is being called 3 times.
For a larger file it comes up even more time. Am I missing something? or a bug?

**Comment by wdavidw** [comment]
Here's my understanding. You complain that `setStatus` is called multiple times. Since only `updateRows` call `setStatus`, it means that `updateRows` is called multiple time. Since it is called from inside the `on('readable')` events, it means that `on('readable')` is called multiple times.

From the [Node.js stream documentation](https://nodejs.org/api/stream.html#stream_event_readable):
> the 'readable' event indicates that the stream has new information: either new data is available or the end of the stream has been reached

It is perfectly normal to have `readable` called multiple times, when the buffer has been processed and new data is coming afterward.
