### ISSUE TITLE
Parser silently hangs.

### ISSUE THREAD

**Issue by Zendor18** [adaltas/node-csv-parse#286]
I'm having trouble with files large then 10mb, or so. I'm using _for await_ interface and parser just silently hangs when i reach about 10-13k rows, no error, nothing, just stops. 

Parser config:
```javascript
const extensions = {
  '.csv': (readableStream)=> readableStream.pipe(parse({
    delimiter: ',',
    quote: '"',
    trim: true,
    bom: true,
    skip_empty_lines: true,
    columns: true,
    relax_column_count: true,
    on_record: (record, context) => {
      const filtered = pickBy(record, (value, key) => !!key);

      return isEmpty(filtered) || context.records === 1 ? null : filtered;
    },
  })),
};
```

**Comment by wdavidw** [comment]
I am pretty sure you are misusing the stream api by not consuming the stream. Once it reach the buffer size, nothing pump the stream and it hangs. Not related to the parser. Your sample doesn't help in understanding your issue, please provide a reproduceable sample, without the 8 unrelevant options present above.

**Comment by Zendor18** [comment]
i'm [using ftp library](https://www.npmjs.com/package/ftp) to download csv files and parse them:

```javascript
    const fileStream = await Promise.race([
      ftpClient.asyncGet(fileName), // get file from ftp
      rejectOnTimeout(10, `timeout: ${fileName}`),
    ]);

  const parser = extensionHandler(fileStream); // this call returning parser that i have showed earlier

  for await (const record of parser) {
      const interpreted = interpreter(record);
      if (Array.isArray(interpreted)) {
        const [data] = interpreted;

        // do some async stuff
      } else {
        const { invalid } = interpreted;

        // do some async stuff
      }
    }
```

Problem not with my async functions because they all resolving, as normal.

**Comment by wdavidw** [comment]
You can start from this working script, it generates 75MB by default:

```js

const generate = require('csv-generate');
const parse = require('.');

(async () => {
  parser = generate({
    high_water_mark: 64 * 64,
    length: 1000*1000
  }).pipe(parse({
    delimiter: ',',
    quote: '"',
    trim: true,
    bom: true,
    skip_empty_lines: true,
    // columns: true,
    relax_column_count: true,
  }))
  let bytes = 0;
  for await (const record of parser) {
    await new Promise((resolve) => {
      bytes += record.join(',').length
      bytes % 1024 === 0 ? setImmediate(resolve) : resolve()
    })
  }
  console.log(`Generated ${Math.round(bytes/1000/1000)} megabytes`)
})()
```

**Comment by Zendor18** [comment]
@wdavidw this code works just fine for me. I found that ftp closes connection after some period of time. And
```javscript
for awat() {}
```
hangs even if i reconnect and resume stream. Is there any good way for reject on timeout or something inside a loop or reject a promise from async iterator? I know it's far from original question, but maybe you can help.

**Comment by wdavidw** [comment]
You can try writing your own `setTimeout` function and call the stream api such as `resume`, `pause` or `destroy`.

**Comment by Zendor18** [comment]
@wdavidw i tried reconnect and resume(), but for await still hangs and not continues.

**Comment by Zendor18** [comment]
@wdavidw And how can i persist headers dynamicly if i use from_line option? because it takes as header line that i start from

**Comment by wdavidw** [comment]
Closing, feel free to re-open if necessary
