### ISSUE TITLE
question: proper options for parsing a TSV file, retrieving exact contents of each field (including quotes)

### ISSUE THREAD

**Issue by rorymc** [adaltas/node-csv-parse#289]
**Is your feature request related to a problem? Please describe.**

question:  is it possible to disable special handling of quoted text, so that when csv-parse is  reading from a stream, it simply splits each line (according to `record_delimiter`) on `delimiter` ?

background:
* reproduced issue with csv-parse version 4.8.8
* parsing a TSV file, where fields may have single or double quotes inside each field
* potentially variable number of fields between different lines
* can guarantee TSV separators are correct for each line of text

desire:
* read each row based on `record_delimiter`, default looks fine for EOL:  `\n`, `\r\n`, or last line i file EOF
* read each field _strictly_ on `delimiter` , no special parsing of `"` included

issues:
* while using the input text example and options/code listed below for reading from a file stream, output doesn't match our desired output noted above
* e.g. for line 2, csv-parse strips the `"` on either side of `Q2 double quoted`.  --> desired output for first field on that line is `"Q2 double quoted"`
* e.g. for line 3, csv-parse will make "field 1":  all of line 3 (because it starts with `"`, through the `\r\n`, and up to the next `"` on line 4 --> desired output for first field on that line is `Q2.3 ending one double quote char"`

input text example:
```
Q1 normal text	A1.1	A2.1	A3.1
"Q2 double quoted"	A1.2	A2.2	A3.2
"Q2.2 beginning one double quote char	A1.2.2	A2.2.2	A3.2.2
Q2.3 ending one double quote char"	A1.2.3	A2.2.3	A3.2.3
quote "Q3 in middle of text" q	A1.3	A2.3	A3.3
quote "Q3 ending text"	A1.3.2	A2.3.2	A3.3.2
"Q4 quote beginning text" q	A1.4	A2.4	A3.4
 "Q5 begin/end with whitespace" 	A1.5	A2.5	A3.5
 "Q6 begin with whitespace and one double quote	A1.6	A2.6	A3.6
Q6.2 end with one double quote and whitespace" 	A1.6.2	A2.6.2	A3.6.2
Q7 "one double quote	A1.7	A2.7	A3.7
Q8 'one single quote	A1.8	A2.8	A3.8
'Q8.2 beginning with one single quote	A1.8.2	A2.8.2	A3.8.2
Q8.3 ending with one single quote'	A1.8.3	A2.8.3	A3.8.3
Q9 'pair of single quotes' case	A1.9	A2.9	A3.9
```

code example:
```
      const parser = parse({
        delimiter: '\t',
        'relax_column_count': true,
        'relax': true,
      });

     // ...

      parser.on('readable', function() {
        for (;;) {
          let record: Array<string> = parser.read();

          if (!record) break;

          // do not want blank columns, so remove all of those.
          record = record
            .map(column => column.trim())
            .filter(column => column.length > 0);

          const firstColumn = record.shift();
          const restOfColumns: Array<any> = [];

          // REF ISSUE

          while (record.length > 0) {
            restOfColumns.push({
              text: record.shift(),
            });
          }

        // ...

        }
      });
```

**Describe the solution you'd like**

* Understand whether there's an option which will give us the output we desire, as noted above

**Describe alternatives you've considered**

* attempted to set `escape` to `null`, but upon reading docs further, realized this is only used _within quoted text_, implying that quoted text smart logic is still being applied
* attempted to set `relax=true`, but that yielded the two issues from line 2 and line 3 of test input example

**Additional context**

None that i can think of, thank you so much for your help.

**Comment by wdavidw** [comment]
If I understood well, your solution is to disable quote. Here is a working script written in CoffeeScript: 

```coffee
parse = require './lib/sync'
assert = require 'assert'

records = parse """
Q1 normal text	A1.1	A2.1	A3.1
"Q2 double quoted"	A1.2	A2.2	A3.2
"Q2.2 beginning one double quote char	A1.2.2	A2.2.2	A3.2.2
""", quote: '', delimiter: '\t'

assert.deepEqual records, [
  [ 'Q1 normal text', 'A1.1', 'A2.1', 'A3.1' ],
  [ '"Q2 double quoted"', 'A1.2', 'A2.2', 'A3.2' ],
  [ '"Q2.2 beginning one double quote char', 'A1.2.2', 'A2.2.2', 'A3.2.2' ]
]
```

**Comment by rorymc** [comment]
hi @wdavidw , wonderful -- do i pass that in as a parameter, _instead of_ `'relax': true,` ?

**Comment by rorymc** [comment]
apologies, i completely missed the option on the [help page](https://csv.js.org/parse/options/):

quote (char|Buffer|boolean)
_Since early days_
Optional character surrounding a field as one character only; disabled if null, false or empty; defaults to double quote.

---

I think the reason i missed that is i searched the page for literal `"`, as i figured the explicit character would be listed.

Thank you for your help !

suggested update for `quote` option help text:

Optional character surrounding a field as one character only; disabled if null, false or empty; defaults to `"` (double quote).

**Comment by wdavidw** [comment]
I will update the document. Do not use `relax`, it is not related to your use case.

**Comment by rorymc** [comment]
really appreciate your quick help on both guidance, and updating the documentation.  thank you !
