### ISSUE TITLE
Multiple column delimiter support

### ISSUE THREAD

**Issue by Fateslayer** [adaltas/node-csv-parse#290]
**Is your feature request related to a problem? Please describe.**
I want to set multiple delimiters for the columns exactly like _record_delimiter_ option which allows you to set an array of delimiters for the rows.

**Describe the solution you'd like**
I would like to have a _column_delimiter_ option which works like _record_delimiter_ but with columns.
```
const parser = parse(file, {
    column_delimiter: [",", ";"]
});
```

**Describe alternatives you've considered**
I'm thinking of replacing the file stream as described in the issue #203 .

**Comment by wdavidw** [comment]
This is a good idea. Not sure I would have much time at the moment, let me know if you wish to participate.

**Comment by Fateslayer** [comment]
> This is a good idea. Not sure I would have much time at the moment, let me know if you wish to participate.

Yeah I'm ready. Let me know how I can help @wdavidw

**Comment by wdavidw** [comment]
you need to normalize the option around line 97, then spot and update all usages of `delimiter`, such as inside `__isDelimiter`, write the appropriate unit tests, and update the TypeScript declaration file. I am available for review when you push the changes

**Comment by Fateslayer** [comment]
So you want to use the existing option called _delimiter_ and not create a new option called _column_delimiter_?

**Comment by wdavidw** [comment]
yes

**Comment by Fateslayer** [comment]
Alright thanks for the guidance. I will begin working on it today and I'll let you know when I'm done.

**Comment by Fateslayer** [comment]
Hey I'm getting this error while running the npm test command
```
'TS_NODE_COMPILER_OPTIONS' is not recognized as an internal or external command,
operable program or batch file.
```
Can you please help me out with this one? I'm running a Windows PC. Thanks!

**Comment by wdavidw** [comment]
Going to the package.json file, you will see the test command is built as `"npm run lint && TS_NODE_COMPILER_OPTIONS='{\"strictNullChecks\":true}' mocha test/**/*.{coffee,ts}"`. I think this is a windows issue which probably doesn't support setting variables before the command. try from a linux like shell (git bash or similar). I am not a windows user and, if related to windows, I can't really help here.

**Comment by Fateslayer** [comment]
Yeah i found the same issue after looking up. Thanks for the help @wdavidw . I'll try bash.

**Comment by Fateslayer** [comment]
I found a solution. I think using this package called [cross-env](https://www.npmjs.com/package/cross-env) will fix the issue for windows users. What do you think? Here's a [stackoverflow post](https://stackoverflow.com/questions/40806796/setting-environment-variables-package-json-in-windows-10) regarding this issue.

**Comment by Fateslayer** [comment]
It worked! After installing the cross-env package, I changed the test command from:
`"test": "npm run lint && TS_NODE_COMPILER_OPTIONS='{\"strictNullChecks\":true}' mocha test/**/*.{coffee,ts}"`
to
`"test": "npm run lint && cross-env TS_NODE_COMPILER_OPTIONS={\\\"strictNullChecks\\\":true} mocha test/**/*.{coffee,ts}"`

**Comment by wdavidw** [comment]
I'll be honest, I am not open to the idea of adding a dev dependency for windows users.

**Comment by Fateslayer** [comment]
Yeah you are right but you can mention this in the documentation maybe.

**Comment by wdavidw** [comment]
Right, on the [development page](https://csv.js.org/project/contribute/) is appropriate.

**Comment by Fateslayer** [comment]
Yeah that's the perfect place for this.

**Comment by Fateslayer** [comment]
I have sent the pull request for the new feature. I hope you'll like it and it will be added to the master branch. Thanks!
