### ISSUE TITLE
Invalid Closing Quote: got "1" at line 1 instead of delimiter, row delimiter, trimable character (if activated) or comment

### ISSUE THREAD

**Issue by HeyKJ** [adaltas/node-csv-parse#293]
**Describe the bug**

A clear and concise description of what the bug is, the CSV package version you are using.

os: win10
node.js: 12.16.0
csv-parse: 4.10.1

```
code: 'CSV_INVALID_CLOSING_QUOTE',
  column: 2,
  empty_lines: 0,
  header: false,
  index: 2,
  invalid_field_length: 0,
  quoting: false,
  lines: 1,
  records: 0
```

**To Reproduce**

Please provide us with a unit test, an example code or even pseudo-code. It could be written in JavaScript or CoffeeScript, it doesn't matter. What's important is to limit the data to the minimum as well as to strip down the number of options to the only ones with an impact.

```
const parse = require('csv-parse/lib/sync')
console.log(parse('`1234`|`10`|`"abc.def"`|`12.12`', { quote: '`', delimiter: '|', escape: '"' }))
```

**Additional context**

```
not working: parse('`1234`|`10`|`"abc.def"`|`12.12`', { quote: '`', delimiter: '|', escape: '"' })  
working (removed " in second index column):  parse('`1234`|`10`|`abc.def`|`12.12`', { quote: '`', delimiter: '|', escape: '"' }) 
```

**Comment by HeyKJ** [comment]
```
// escape: ' ' works
parse('`1234`|`10`|`"abc.def"`|`12.12`', { quote: '`', delimiter: '|', escape: ' ' })
```

**Comment by wdavidw** [comment]
Version 4.11.1 allows a `false` or `null` value to disable the escaping (much better than passing an empty space).
