### ISSUE TITLE
Invalid Opening Quote with utf-16 little endian content

### ISSUE THREAD

**Issue by jgeurts** [adaltas/node-csv-parse#299]
I've had some issues when passing a buffer that is a utf-16 little endian. Even when I convert the buffer to a string, with `utf16le` encoding, I get an error like `Invalid Opening Quote: a quote is found inside a field at line 2`. This is occurring with csv-parse version 4.12.0. This is running on node 12 (transpiled from typescript).

**To Reproduce**

```
import { promises as fs } from 'fs';
import parse from 'csv-parse';

async function test() {
  const inputBuffer = await fs.readFile(path.join(__dirname, './test.csv'));
  const parser = parse(inputBuffer, {
    columns: true,
    cast: false,
    bom: true,
    delimiter: '\t',
  });

  for await (const row of parser) {
    console.log(JSON.stringify(row));
  }
}
```

[test.csv.txt](https://github.com/adaltas/node-csv-parse/files/5468259/test.csv.txt)

**Comment by jgeurts** [comment]
In case the original csv lost some of the tabs, try this one
[test.csv.txt](https://github.com/adaltas/node-csv-parse/files/5468286/test.csv.txt)

**Comment by jgeurts** [comment]
I have been able to get things working when I do something like the following. I'm curious if it's possible to avoid converting the buffer to string?

```
import { promises as fs } from 'fs';
import parse from 'csv-parse';

async function test() {
  const inputBuffer = await fs.readFile(path.join(__dirname, './test.csv'));
  let inputContent = inputBuffer.toString('utf8');
  if (inputContent.charCodeAt(0) === 0xfffd) {
    inputContent = inputBuffer.toString('utf16le');
  }

  const parser = parse(inputContent, {
    columns: true,
    cast: false,
    bom: true,
    delimiter: '\t',
  });

  for await (const row of parser) {
    console.log(JSON.stringify(row));
  }
}
```

**Comment by wdavidw** [comment]
Hi @jgeurts, you need to indicate the source encoding when reading the file. The `fs.readFile` function shall be called as `await fs.readFile('./test.csv', {encoding: 'utf16le'});`.

**Comment by jgeurts** [comment]
What if I don't know the source encoding ahead of time, though? Could the `bom` option account for this type of encoding, too?

**Comment by wdavidw** [comment]
Hi @jgeurts, you kind of consumed my last 2 days of work. Try version 4.13, it comes with the [new encoding option](https://csv.js.org/parse/options/encoding/) and my tests are working with your data source. The next step would be to introduce `encoding_input` and `encoding_output` to differentiate the encoding used between the stream writer and the stream reader but I leave it for the future or to someone else.

**Comment by jgeurts** [comment]
Sorry that it consumed you, but this is really awesome, thank you! The `encoding_input` and `encoding_output` would be great, but totally understand waiting on those.
