### ISSUE TITLE
Skip event for error line should provide raw data 

### ISSUE THREAD

**Issue by sanchit-aneja** [adaltas/node-csv-parse#301]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wdavidw** [comment]
Please a complete bug report.

**Comment by sanchit-aneja** [comment]
I have provide the description of my problem above

**Comment by wdavidw** [comment]
It seems like you could use a combinaison of the `relax_column_count`, `on_record` and `raw` options. I have updated the [`relax_colunn_count`](https://csv.js.org/parse/options/relax_column_count/#handling-inconsistent-number-of-fields-errors) documentation in that regard.

Note, the usage of error like in the example requires the latest version.

**Comment by sanchit-aneja** [comment]
It found my mistake. Its Solved 
Thanks
