### ISSUE TITLE
Module not found: Error: Can't resolve 'stream' in node_modules\csv-parse\lib\es5

### ISSUE THREAD

**Issue by kzkzg** [adaltas/node-csv-parse#302]
After update from Angular 5 to 6, I have this compile error.

`ERROR in ./node_modules/csv-parse/lib/es5/index.js
Module not found: Error: Can't resolve 'stream' in '<projectPath>\node_modules\csv-parse\lib\es5'`

Package version 4.14.0
What am I doing wrong? Please help

**Comment by wdavidw** [comment]
You seem to be in a browser environnement. You need to use sth like webpack.

**Comment by kzkzg** [comment]
> You seem to be in a browser environnement. You need to use sth like webpack.

I'm staring it by `ng serve` from angular

**Comment by wdavidw** [comment]
Try to use a tool like [browserify](http://browserify.org/)

**Comment by igabesz** [comment]
Angular has a preconfigured build system that is not to be tampered with in most cases. If it won't work with the default builder then this package is practically unusable in Angular.

**Comment by darkguy2008** [comment]
I agree, just stumbled upon this issue as well. Such a good library that comes up in search results but it's practically unusable in Angular or anything that doesn't require custom webpack modifications, and the workaround of using browserify is just laughable.

**Comment by wdavidw** [comment]
No wait! I made it worked for csv-stringify. Give me an hour and I will publish a working version with a demo.

**Comment by wdavidw** [comment]
I just published version v4.15.2, you can have a look at this [demo](https://github.com/adaltas/node-csv-parse/tree/master/samples/browser). It uses the HTML `<script>` tag without any external code and it gives access to the `parse` function. Let us know if it works for you with angular.

**Comment by webstoreportal** [comment]
Another issue-reply mentioned to use es5 - that did not work

Assuming `node` issues. Hard to track down any recent workarounds with this or in general for Angular projects

`lib/browser` seems to get past the initial `prototype` etc resolution issues with `csv`; however, it does not have a declaration file for poor importability?

Angular TypeScript

may be better to use one of the many angular csv packages around

**Comment by webstoreportal** [comment]
Adding here as a faster workaround to get up and running from a search engine search -
I used Papa Parse - explicitly advertised for in-browser parsing

`npm i papaparse` 

_It just works_. 600k weekly downloads. Simple single dependency. Seems extremely fast. Decent intellisense usage with documented comments and the documentation first page overview easy to use.

Would have preferred to use something well-supported like `csv`, 300k weekly downloads with a great name; however, the hours saved for a simple import into web app usage in this personal use case are indisputable.

May come back to `csv` for `node`-specific usage

**Comment by wdavidw** [comment]
You can also help by providing a simple angular repository reproducing the problem, from there, I can work on it to better understand what the problem is and fix it.
