### ISSUE TITLE
strange behavior in scopes

### ISSUE THREAD

**Issue by Osolemio44** [adaltas/node-csv-parse#306]
I am creating a super simple application. I declare a general variable but then when printing to console it gives me different values depending on whether I put the "console.log" inside or outside the function. This should not happen since my variable is declared in the upper scope and therefore it should keep the changes made within the function. This is a bug? Or is it some intentional behavior that I can't understand?

info:
Window 10
VSCode 1.52.1
Node 14.15.4
csv-parser 3.0.0

this is my app code:

```
const csv = require('csv-parser')
const createCsvWriter = require('csv-writer').createObjectCsvWriter;
const fs = require('fs')
let results = [];


fs.createReadStream('./input/BTX-quinceminutales_07-01-2021.txt')
    .pipe(csv({ separator: ';' }))
    .on('data', (data) => {

        let obj = {};
        for (const [key, value] of Object.entries(data)) {
            if (key == 'FECHA HORA') {
                obj["FECHA"] = value.split(' ')[0];
                obj['HORA'] = value.split(' ')[1];
            } else {
                obj[key] = value;
            }
        }
        //check to not add empty object
        if (Object.keys(obj).length !== 0 && obj.constructor === Object) {
            results.push(obj);
        }
    }
    )
    .on('end', () => {
        //console.log('results :>> ', results);
    });
console.log('results :>> ', results);
```

https://user-images.githubusercontent.com/55595063/104133956-21576c80-5387-11eb-989c-7b1c561ff704.mp4

**Comment by wdavidw** [comment]
This is a JavaScript question and your results are expected. The function `fs.createReadStream` as well as the CSV parser are run asynchronously, they don't block the process execution. Either learn how to use JavaScript with asynchronous functions and the Node.js stream API or simply use the [CSV sync API](https://csv.js.org/parse/api/sync/).
