### ISSUE TITLE
Comma inside cell

### ISSUE THREAD

**Issue by justin-dx** [adaltas/node-csv-parse#311]
From my reading of the docs the default config should treat cells that are surrounded with double quotes as a single cell.
So my data of `Mary, Johnson, "m,johnson"` should be treated as 3 cells `Mary`, `Johnson` and `m,johnson`, but when parsing I get 4 cells - `Mary`, `Johnson`, `m` and `johnson`.
What am I doing wrong?

**Comment by wdavidw** [comment]
You have spaces around you quotes, take a look a the `trim` options
