### ISSUE TITLE
Switch to camelCase option names

### ISSUE THREAD

**Issue by rayfoss** [adaltas/node-csv-parse#322]
**Is your feature request related to a problem? Please describe.**

Standard, Vue and React all lint against snake casing. Snakes also cause issues with fonts and cut out at certain sizes, creating errors. https://github.com/microsoft/vscode/issues/35901

**Describe the solution you'd like**

For version 5 ish, deprecate and log a message. Remove in version 6.

**Describe alternatives you've considered**

I've considered learning French, it's not for me.

**Additional context**

https://eslint.org/docs/rules/camelcase

**Comment by wdavidw** [comment]
There is no reason to change. CamelCase is your preference and it is supported. It is not mine and everyone is satisfied.
