### ISSUE TITLE
Subclassed errors

### ISSUE THREAD

**Issue by rhys-vdw** [adaltas/node-csv-parse#39]
Just wondering if there has been any consideration has been put to subclassing the syntax errors thrown from this module?

I'm using NodeCSV in [Bluebird](https://github.com/petkaantonov/bluebird) promise chains and would like to be able to catch errors by type.

For example:

``` CoffeeScript
Promise = require 'bluebird'
fs = Promise.promisifyAll require 'fs'
csv = Promise.promisifyAll require 'csv'
other = require './other'

fs.readFileAsync path
.then (data) -> csv.parseAsync data
.then (parsed) -> other(parsed)
.catch csv.CsvSyntaxError, (error) ->
  console.error 'CSV has a syntax error', error
.catch (error) ->
  console.error 'Unexpected error', error
```

At the moment the best way to differentiate errors is to do a string search for `'Invalid (opening|closing) quote'` in `error.message`, which is quite brittle.

**Comment by wdavidw** [comment]
It's a good idea but I'll go for `err.code` instead of class

**Comment by rhys-vdw** [comment]
I think subclassing is more idiomatic, even if it's just one error class for all of NodeCSV, with a code to differentiate between specific errors. The main issue here is to tell whether an errors comes from NodeCSV rather than a different module (a code primarily helps to differentiate different NodeCSV errors). So if a `code` property is used I'd still need to do something like this:

```CoffeeScript
isNodeCsvError = (error) ->
  if !error.code
    return false
  codes = [ 'a-code', 'another-code', 'some-other' ]
  return _.contains codes, error.code

csv.parseAsync data
.catch isNodeCsvError, (error) -> dealWithCsvError(error)
```

The problem here being that if a new error code is added, my code wont catch it. Just checking for the presence of `code` might be sufficient, but only if other modules do not provide a `code` property on their errors.

**Comment by wdavidw** [comment]
Problem with subclassing in js is that instanceof doesnt work if multiples version of the package are installed. Also, i'll rather stick to node.js standards

**Comment by rhys-vdw** [comment]
Fair enough. That is indeed a problem. Cheers.

**Comment by wdavidw** [comment]
we could use a mix of the two solutions, subclassing + code. if you want to prepare a patch this way, ill apply it

**Comment by rhys-vdw** [comment]
Thanks. I'll try to get around to it next week.

**Comment by jonathansamines** [comment]
I am really interested in having support for at least "codes", So I can provide my user with good error messages (localised). Is there any plan to add support to them or accept a PR to add this support?

**Comment by wdavidw** [comment]
I would accept PRs introducing code in errors

**Comment by wdavidw** [comment]
Doing some house cleaning. Feel free to open a new issue if needed.
