### ISSUE TITLE
Quotes are included in output when parsing with relax: true, trim: true

### ISSUE THREAD

**Issue by jasoncrawford** [adaltas/node-csv-parse#62]
Repro:

```
csv.parse('"A" , "B" , "C"', {relax: true, trim: true}, function (error, output) { console.log(output) })
```

Expected:

```
[ [ 'A', 'B', 'C' ] ]
```

Actual:

```
[ [ '"A"', '"B"', 'C' ] ]
```

This worked in `csv-parse@0.0.6`. Just upgraded to 1.0.0 (via `csv@0.4.6`) and I'm seeing this new, unexpected behavior.

**Comment by wdavidw** [comment]
i could be bugged, i never considered parse as stable but more in the philosophy "ok, you got invalid csv, if parse can help you, use it". If i remember, i tried to work around this probleme not so long ago and give up. it's actually quite hard to fix but possible of course

**Comment by wdavidw** [comment]
old issue, closing
